export type AM600Question = {
  id: number
  title: string
  slug: string
  difficulty: 'Easy' | 'Medium' | 'Hard'
}

export type AM600Category = {
  name: string
  emoji: string
  color: string
  questions: AM600Question[]
}

export const ALGOMASTER_600: AM600Category[] = [
  {
    name: 'Arrays', emoji: '📦', color: 'indigo',
    questions: [
      { id: 485, title: 'Max Consecutive Ones', slug: 'max-consecutive-ones', difficulty: 'Easy' },
      { id: 414, title: 'Third Maximum Number', slug: 'third-maximum-number', difficulty: 'Easy' },
      { id: 283, title: 'Move Zeroes', slug: 'move-zeroes', difficulty: 'Easy' },
      { id: 1470, title: 'Shuffle the Array', slug: 'shuffle-the-array', difficulty: 'Easy' },
      { id: 169, title: 'Majority Element', slug: 'majority-element', difficulty: 'Easy' },
      { id: 26, title: 'Remove Duplicates from Sorted Array', slug: 'remove-duplicates-from-sorted-array', difficulty: 'Easy' },
      { id: 27, title: 'Remove Element', slug: 'remove-element', difficulty: 'Easy' },
      { id: 121, title: 'Best Time to Buy and Sell Stock', slug: 'best-time-to-buy-and-sell-stock', difficulty: 'Easy' },
      { id: 163, title: 'Missing Ranges', slug: 'missing-ranges', difficulty: 'Easy' },
      { id: 229, title: 'Majority Element II', slug: 'majority-element-ii', difficulty: 'Medium' },
      { id: 189, title: 'Rotate Array', slug: 'rotate-array', difficulty: 'Medium' },
      { id: 238, title: 'Product of Array Except Self', slug: 'product-of-array-except-self', difficulty: 'Medium' },
      { id: 80, title: 'Remove Duplicates from Sorted Array II', slug: 'remove-duplicates-from-sorted-array-ii', difficulty: 'Medium' },
      { id: 122, title: 'Best Time to Buy and Sell Stock II', slug: 'best-time-to-buy-and-sell-stock-ii', difficulty: 'Medium' },
      { id: 2348, title: 'Number of Zero-Filled Subarrays', slug: 'number-of-zero-filled-subarrays', difficulty: 'Medium' },
      { id: 334, title: 'Increasing Triplet Subsequence', slug: 'increasing-triplet-subsequence', difficulty: 'Medium' },
      { id: 31, title: 'Next Permutation', slug: 'next-permutation', difficulty: 'Medium' },
      { id: 41, title: 'First Missing Positive', slug: 'first-missing-positive', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Strings', emoji: '🔤', color: 'cyan',
    questions: [
      { id: 344, title: 'Reverse String', slug: 'reverse-string', difficulty: 'Easy' },
      { id: 58, title: 'Length of Last Word', slug: 'length-of-last-word', difficulty: 'Easy' },
      { id: 392, title: 'Is Subsequence', slug: 'is-subsequence', difficulty: 'Easy' },
      { id: 125, title: 'Valid Palindrome', slug: 'valid-palindrome', difficulty: 'Easy' },
      { id: 680, title: 'Valid Palindrome II', slug: 'valid-palindrome-ii', difficulty: 'Easy' },
      { id: 242, title: 'Valid Anagram', slug: 'valid-anagram', difficulty: 'Easy' },
      { id: 796, title: 'Rotate String', slug: 'rotate-string', difficulty: 'Easy' },
      { id: 14, title: 'Longest Common Prefix', slug: 'longest-common-prefix', difficulty: 'Easy' },
      { id: 409, title: 'Longest Palindrome', slug: 'longest-palindrome', difficulty: 'Easy' },
      { id: 28, title: 'Find the Index of the First Occurrence in a String', slug: 'find-the-index-of-the-first-occurrence-in-a-string', difficulty: 'Easy' },
      { id: 161, title: 'One Edit Distance', slug: 'one-edit-distance', difficulty: 'Medium' },
      { id: 6, title: 'Zigzag Conversion', slug: 'zigzag-conversion', difficulty: 'Medium' },
      { id: 38, title: 'Count and Say', slug: 'count-and-say', difficulty: 'Medium' },
      { id: 151, title: 'Reverse Words in a String', slug: 'reverse-words-in-a-string', difficulty: 'Medium' },
      { id: 1657, title: 'Determine if Two Strings Are Close', slug: 'determine-if-two-strings-are-close', difficulty: 'Medium' },
      { id: 616, title: 'Add Bold Tag in String', slug: 'add-bold-tag-in-string', difficulty: 'Medium' },
      { id: 68, title: 'Text Justification', slug: 'text-justification', difficulty: 'Hard' },
      { id: 843, title: 'Guess the Word', slug: 'guess-the-word', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Bit Manipulation', emoji: '⚡', color: 'sky',
    questions: [
      { id: 136, title: 'Single Number', slug: 'single-number', difficulty: 'Easy' },
      { id: 268, title: 'Missing Number', slug: 'missing-number', difficulty: 'Easy' },
      { id: 645, title: 'Set Mismatch', slug: 'set-mismatch', difficulty: 'Easy' },
      { id: 231, title: 'Power of Two', slug: 'power-of-two', difficulty: 'Easy' },
      { id: 191, title: 'Number of 1 Bits', slug: 'number-of-1-bits', difficulty: 'Easy' },
      { id: 338, title: 'Counting Bits', slug: 'counting-bits', difficulty: 'Easy' },
      { id: 461, title: 'Hamming Distance', slug: 'hamming-distance', difficulty: 'Easy' },
      { id: 190, title: 'Reverse Bits', slug: 'reverse-bits', difficulty: 'Easy' },
      { id: 201, title: 'Bitwise AND of Numbers Range', slug: 'bitwise-and-of-numbers-range', difficulty: 'Medium' },
      { id: 137, title: 'Single Number II', slug: 'single-number-ii', difficulty: 'Medium' },
      { id: 260, title: 'Single Number III', slug: 'single-number-iii', difficulty: 'Medium' },
      { id: 371, title: 'Sum of Two Integers', slug: 'sum-of-two-integers', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Hash Tables', emoji: '🔑', color: 'orange',
    questions: [
      { id: 706, title: 'Design HashMap', slug: 'design-hashmap', difficulty: 'Easy' },
      { id: 217, title: 'Contains Duplicate', slug: 'contains-duplicate', difficulty: 'Easy' },
      { id: 290, title: 'Word Pattern', slug: 'word-pattern', difficulty: 'Easy' },
      { id: 387, title: 'First Unique Character in a String', slug: 'first-unique-character-in-a-string', difficulty: 'Easy' },
      { id: 448, title: 'Find All Numbers Disappeared in an Array', slug: 'find-all-numbers-disappeared-in-an-array', difficulty: 'Easy' },
      { id: 1189, title: 'Maximum Number of Balloons', slug: 'maximum-number-of-balloons', difficulty: 'Easy' },
      { id: 1512, title: 'Number of Good Pairs', slug: 'number-of-good-pairs', difficulty: 'Easy' },
      { id: 205, title: 'Isomorphic Strings', slug: 'isomorphic-strings', difficulty: 'Easy' },
      { id: 383, title: 'Ransom Note', slug: 'ransom-note', difficulty: 'Easy' },
      { id: 219, title: 'Contains Duplicate II', slug: 'contains-duplicate-ii', difficulty: 'Easy' },
      { id: 350, title: 'Intersection of Two Arrays II', slug: 'intersection-of-two-arrays-ii', difficulty: 'Easy' },
      { id: 49, title: 'Group Anagrams', slug: 'group-anagrams', difficulty: 'Medium' },
      { id: 535, title: 'Encode and Decode TinyURL', slug: 'encode-and-decode-tinyurl', difficulty: 'Medium' },
      { id: 767, title: 'Reorganize String', slug: 'reorganize-string', difficulty: 'Medium' },
      { id: 128, title: 'Longest Consecutive Sequence', slug: 'longest-consecutive-sequence', difficulty: 'Medium' },
      { id: 659, title: 'Split Array into Consecutive Subsequences', slug: 'split-array-into-consecutive-subsequences', difficulty: 'Medium' },
      { id: 792, title: 'Number of Matching Subsequences', slug: 'number-of-matching-subsequences', difficulty: 'Medium' },
      { id: 1525, title: 'Number of Good Ways to Split a String', slug: 'number-of-good-ways-to-split-a-string', difficulty: 'Medium' },
      { id: 249, title: 'Group Shifted Strings', slug: 'group-shifted-strings', difficulty: 'Medium' },
      { id: 1647, title: 'Minimum Deletions to Make Character Frequencies Unique', slug: 'minimum-deletions-to-make-character-frequencies-unique', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Two Pointers', emoji: '👆', color: 'violet',
    questions: [
      { id: 88, title: 'Merge Sorted Array', slug: 'merge-sorted-array', difficulty: 'Easy' },
      { id: 1768, title: 'Merge Strings Alternately', slug: 'merge-strings-alternately', difficulty: 'Easy' },
      { id: 977, title: 'Squares of a Sorted Array', slug: 'squares-of-a-sorted-array', difficulty: 'Easy' },
      { id: 1, title: 'Two Sum', slug: 'two-sum', difficulty: 'Easy' },
      { id: 844, title: 'Backspace String Compare', slug: 'backspace-string-compare', difficulty: 'Easy' },
      { id: 408, title: 'Valid Word Abbreviation', slug: 'valid-word-abbreviation', difficulty: 'Easy' },
      { id: 696, title: 'Count Binary Substrings', slug: 'count-binary-substrings', difficulty: 'Easy' },
      { id: 167, title: 'Two Sum II - Input Array Is Sorted', slug: 'two-sum-ii-input-array-is-sorted', difficulty: 'Medium' },
      { id: 11, title: 'Container With Most Water', slug: 'container-with-most-water', difficulty: 'Medium' },
      { id: 15, title: '3Sum', slug: '3sum', difficulty: 'Medium' },
      { id: 18, title: '4Sum', slug: '4sum', difficulty: 'Medium' },
      { id: 443, title: 'String Compression', slug: 'string-compression', difficulty: 'Medium' },
      { id: 861, title: 'Boats to Save People', slug: 'boats-to-save-people', difficulty: 'Medium' },
      { id: 5, title: 'Longest Palindromic Substring', slug: 'longest-palindromic-substring', difficulty: 'Medium' },
      { id: 42, title: 'Trapping Rain Water', slug: 'trapping-rain-water', difficulty: 'Hard' },
      { id: 2444, title: 'Count Subarrays With Fixed Bounds', slug: 'count-subarrays-with-fixed-bounds', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Prefix Sum', emoji: '➕', color: 'teal',
    questions: [
      { id: 1480, title: 'Running Sum of 1d Array', slug: 'running-sum-of-1d-array', difficulty: 'Easy' },
      { id: 303, title: 'Range Sum Query - Immutable', slug: 'range-sum-query-immutable', difficulty: 'Easy' },
      { id: 724, title: 'Find Pivot Index', slug: 'find-pivot-index', difficulty: 'Easy' },
      { id: 1854, title: 'Maximum Population Year', slug: 'maximum-population-year', difficulty: 'Easy' },
      { id: 370, title: 'Range Addition', slug: 'range-addition', difficulty: 'Medium' },
      { id: 560, title: 'Subarray Sum Equals K', slug: 'subarray-sum-equals-k', difficulty: 'Medium' },
      { id: 974, title: 'Subarray Sums Divisible by K', slug: 'subarray-sums-divisible-by-k', difficulty: 'Medium' },
      { id: 523, title: 'Continuous Subarray Sum', slug: 'continuous-subarray-sum', difficulty: 'Medium' },
      { id: 525, title: 'Contiguous Array', slug: 'contiguous-array', difficulty: 'Medium' },
      { id: 304, title: 'Range Sum Query 2D - Immutable', slug: 'range-sum-query-2d-immutable', difficulty: 'Medium' },
      { id: 2536, title: 'Increment Submatrices by One', slug: 'increment-submatrices-by-one', difficulty: 'Medium' },
      { id: 1314, title: 'Matrix Block Sum', slug: 'matrix-block-sum', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Sliding Window - Fixed Size', emoji: '🪟', color: 'green',
    questions: [
      { id: 643, title: 'Maximum Average Subarray I', slug: 'maximum-average-subarray-i', difficulty: 'Easy' },
      { id: 438, title: 'Find All Anagrams in a String', slug: 'find-all-anagrams-in-a-string', difficulty: 'Medium' },
      { id: 567, title: 'Permutation in String', slug: 'permutation-in-string', difficulty: 'Medium' },
      { id: 1456, title: 'Maximum Number of Vowels in a Substring of Given Length', slug: 'maximum-number-of-vowels-in-a-substring-of-given-length', difficulty: 'Medium' },
      { id: 2461, title: 'Maximum Sum of Distinct Subarrays With Length K', slug: 'maximum-sum-of-distinct-subarrays-with-length-k', difficulty: 'Medium' },
      { id: 30, title: 'Substring with Concatenation of All Words', slug: 'substring-with-concatenation-of-all-words', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Sliding Window - Dynamic Size', emoji: '🎯', color: 'fuchsia',
    questions: [
      { id: 3, title: 'Longest Substring Without Repeating Characters', slug: 'longest-substring-without-repeating-characters', difficulty: 'Medium' },
      { id: 424, title: 'Longest Repeating Character Replacement', slug: 'longest-repeating-character-replacement', difficulty: 'Medium' },
      { id: 209, title: 'Minimum Size Subarray Sum', slug: 'minimum-size-subarray-sum', difficulty: 'Medium' },
      { id: 1004, title: 'Max Consecutive Ones III', slug: 'max-consecutive-ones-iii', difficulty: 'Medium' },
      { id: 1248, title: 'Count Number of Nice Subarrays', slug: 'count-number-of-nice-subarrays', difficulty: 'Medium' },
      { id: 904, title: 'Fruit Into Baskets', slug: 'fruit-into-baskets', difficulty: 'Medium' },
      { id: 1423, title: 'Maximum Points You Can Obtain from Cards', slug: 'maximum-points-you-can-obtain-from-cards', difficulty: 'Medium' },
      { id: 713, title: 'Subarray Product Less Than K', slug: 'subarray-product-less-than-k', difficulty: 'Medium' },
      { id: 1838, title: 'Frequency of the Most Frequent Element', slug: 'frequency-of-the-most-frequent-element', difficulty: 'Medium' },
      { id: 159, title: 'Longest Substring with At Most Two Distinct Characters', slug: 'longest-substring-with-at-most-two-distinct-characters', difficulty: 'Medium' },
      { id: 340, title: 'Longest Substring with At Most K Distinct Characters', slug: 'longest-substring-with-at-most-k-distinct-characters', difficulty: 'Medium' },
      { id: 395, title: 'Longest Substring with At Least K Repeating Characters', slug: 'longest-substring-with-at-least-k-repeating-characters', difficulty: 'Medium' },
      { id: 76, title: 'Minimum Window Substring', slug: 'minimum-window-substring', difficulty: 'Hard' },
      { id: 727, title: 'Minimum Window Subsequence', slug: 'minimum-window-subsequence', difficulty: 'Hard' },
      { id: 992, title: 'Subarrays with K Different Integers', slug: 'subarrays-with-k-different-integers', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Kadane\'s Algorithm', emoji: '📈', color: 'rose',
    questions: [
      { id: 53, title: 'Maximum Subarray', slug: 'maximum-subarray', difficulty: 'Medium' },
      { id: 918, title: 'Maximum Sum Circular Subarray', slug: 'maximum-sum-circular-subarray', difficulty: 'Medium' },
      { id: 1186, title: 'Maximum Subarray Sum with One Deletion', slug: 'maximum-subarray-sum-with-one-deletion', difficulty: 'Medium' },
      { id: 1749, title: 'Maximum Absolute Sum of Any Subarray', slug: 'maximum-absolute-sum-of-any-subarray', difficulty: 'Medium' },
      { id: 152, title: 'Maximum Product Subarray', slug: 'maximum-product-subarray', difficulty: 'Medium' },
      { id: 978, title: 'Longest Turbulent Subarray', slug: 'longest-turbulent-subarray', difficulty: 'Medium' },
      { id: 1014, title: 'Best Sightseeing Pair', slug: 'best-sightseeing-pair', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Matrix (2D Array)', emoji: '🔲', color: 'amber',
    questions: [
      { id: 867, title: 'Transpose Matrix', slug: 'transpose-matrix', difficulty: 'Easy' },
      { id: 54, title: 'Spiral Matrix', slug: 'spiral-matrix', difficulty: 'Medium' },
      { id: 59, title: 'Spiral Matrix II', slug: 'spiral-matrix-ii', difficulty: 'Medium' },
      { id: 498, title: 'Diagonal Traverse', slug: 'diagonal-traverse', difficulty: 'Medium' },
      { id: 48, title: 'Rotate Image', slug: 'rotate-image', difficulty: 'Medium' },
      { id: 73, title: 'Set Matrix Zeroes', slug: 'set-matrix-zeroes', difficulty: 'Medium' },
      { id: 723, title: 'Candy Crush', slug: 'candy-crush', difficulty: 'Medium' },
      { id: 36, title: 'Valid Sudoku', slug: 'valid-sudoku', difficulty: 'Medium' },
      { id: 289, title: 'Game of Life', slug: 'game-of-life', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Linked List', emoji: '🔗', color: 'blue',
    questions: [
      { id: 160, title: 'Intersection of Two Linked Lists', slug: 'intersection-of-two-linked-lists', difficulty: 'Easy' },
      { id: 83, title: 'Remove Duplicates from Sorted List', slug: 'remove-duplicates-from-sorted-list', difficulty: 'Easy' },
      { id: 707, title: 'Design Linked List', slug: 'design-linked-list', difficulty: 'Medium' },
      { id: 2095, title: 'Delete the Middle Node of a Linked List', slug: 'delete-the-middle-node-of-a-linked-list', difficulty: 'Medium' },
      { id: 19, title: 'Remove Nth Node From End of List', slug: 'remove-nth-node-from-end-of-list', difficulty: 'Medium' },
      { id: 82, title: 'Remove Duplicates from Sorted List II', slug: 'remove-duplicates-from-sorted-list-ii', difficulty: 'Medium' },
      { id: 328, title: 'Odd Even Linked List', slug: 'odd-even-linked-list', difficulty: 'Medium' },
      { id: 24, title: 'Swap Nodes in Pairs', slug: 'swap-nodes-in-pairs', difficulty: 'Medium' },
      { id: 138, title: 'Copy List with Random Pointer', slug: 'copy-list-with-random-pointer', difficulty: 'Medium' },
      { id: 86, title: 'Partition List', slug: 'partition-list', difficulty: 'Medium' },
      { id: 61, title: 'Rotate List', slug: 'rotate-list', difficulty: 'Medium' },
      { id: 143, title: 'Reorder List', slug: 'reorder-list', difficulty: 'Medium' },
      { id: 2, title: 'Add Two Numbers', slug: 'add-two-numbers', difficulty: 'Medium' },
      { id: 445, title: 'Add Two Numbers II', slug: 'add-two-numbers-ii', difficulty: 'Medium' },
      { id: 237, title: 'Delete Node in a Linked List', slug: 'delete-node-in-a-linked-list', difficulty: 'Medium' },
      { id: 430, title: 'Flatten a Multilevel Doubly Linked List', slug: 'flatten-a-multilevel-doubly-linked-list', difficulty: 'Medium' },
      { id: 708, title: 'Insert into a Sorted Circular Linked List', slug: 'insert-into-a-sorted-circular-linked-list', difficulty: 'Medium' },
      { id: 1669, title: 'Merge In Between Linked Lists', slug: 'merge-in-between-linked-lists', difficulty: 'Medium' },
    ],
  },
  {
    name: 'LinkedList In-place Reversal', emoji: '🔄', color: 'purple',
    questions: [
      { id: 234, title: 'Palindrome Linked List', slug: 'palindrome-linked-list', difficulty: 'Easy' },
      { id: 206, title: 'Reverse Linked List', slug: 'reverse-linked-list', difficulty: 'Easy' },
      { id: 92, title: 'Reverse Linked List II', slug: 'reverse-linked-list-ii', difficulty: 'Medium' },
      { id: 25, title: 'Reverse Nodes in k-Group', slug: 'reverse-nodes-in-k-group', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Fast and Slow Pointers', emoji: '🐢', color: 'emerald',
    questions: [
      { id: 876, title: 'Middle of the Linked List', slug: 'middle-of-the-linked-list', difficulty: 'Easy' },
      { id: 202, title: 'Happy Number', slug: 'happy-number', difficulty: 'Easy' },
      { id: 141, title: 'Linked List Cycle II', slug: 'linked-list-cycle-ii', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Stacks', emoji: '📚', color: 'lime',
    questions: [
      { id: 20, title: 'Valid Parentheses', slug: 'valid-parentheses', difficulty: 'Easy' },
      { id: 682, title: 'Baseball Game', slug: 'baseball-game', difficulty: 'Easy' },
      { id: 1047, title: 'Remove All Adjacent Duplicates In String', slug: 'remove-all-adjacent-duplicates-in-string', difficulty: 'Easy' },
      { id: 1614, title: 'Maximum Nesting Depth of the Parentheses', slug: 'maximum-nesting-depth-of-the-parentheses', difficulty: 'Easy' },
      { id: 155, title: 'Min Stack', slug: 'min-stack', difficulty: 'Medium' },
      { id: 735, title: 'Asteroid Collision', slug: 'asteroid-collision', difficulty: 'Medium' },
      { id: 853, title: 'Car Fleet', slug: 'car-fleet', difficulty: 'Medium' },
      { id: 678, title: 'Valid Parenthesis String', slug: 'valid-parenthesis-string', difficulty: 'Medium' },
      { id: 946, title: 'Validate Stack Sequences', slug: 'validate-stack-sequences', difficulty: 'Medium' },
      { id: 1249, title: 'Minimum Remove to Make Valid Parentheses', slug: 'minimum-remove-to-make-valid-parentheses', difficulty: 'Medium' },
      { id: 316, title: 'Remove Duplicate Letters', slug: 'remove-duplicate-letters', difficulty: 'Medium' },
      { id: 2390, title: 'Removing Stars From a String', slug: 'removing-stars-from-a-string', difficulty: 'Medium' },
      { id: 71, title: 'Simplify Path', slug: 'simplify-path', difficulty: 'Medium' },
      { id: 636, title: 'Exclusive Time of Functions', slug: 'exclusive-time-of-functions', difficulty: 'Medium' },
      { id: 150, title: 'Evaluate Reverse Polish Notation', slug: 'evaluate-reverse-polish-notation', difficulty: 'Medium' },
      { id: 227, title: 'Basic Calculator II', slug: 'basic-calculator-ii', difficulty: 'Medium' },
      { id: 224, title: 'Basic Calculator', slug: 'basic-calculator', difficulty: 'Medium' },
      { id: 32, title: 'Longest Valid Parentheses', slug: 'longest-valid-parentheses', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Monotonic Stack', emoji: '📐', color: 'yellow',
    questions: [
      { id: 496, title: 'Next Greater Element I', slug: 'next-greater-element-i', difficulty: 'Easy' },
      { id: 1475, title: 'Final Prices With a Special Discount in a Shop', slug: 'final-prices-with-a-special-discount-in-a-shop', difficulty: 'Easy' },
      { id: 503, title: 'Next Greater Element II', slug: 'next-greater-element-ii', difficulty: 'Medium' },
      { id: 739, title: 'Daily Temperatures', slug: 'daily-temperatures', difficulty: 'Medium' },
      { id: 901, title: 'Online Stock Span', slug: 'online-stock-span', difficulty: 'Medium' },
      { id: 1762, title: 'Buildings With an Ocean View', slug: 'buildings-with-an-ocean-view', difficulty: 'Medium' },
      { id: 456, title: '132 Pattern', slug: '132-pattern', difficulty: 'Medium' },
      { id: 402, title: 'Remove K Digits', slug: 'remove-k-digits', difficulty: 'Medium' },
      { id: 962, title: 'Maximum Width Ramp', slug: 'maximum-width-ramp', difficulty: 'Medium' },
      { id: 769, title: 'Max Chunks To Make Sorted', slug: 'max-chunks-to-make-sorted', difficulty: 'Medium' },
      { id: 907, title: 'Sum of Subarray Minimums', slug: 'sum-of-subarray-minimums', difficulty: 'Medium' },
      { id: 2104, title: 'Sum of Subarray Ranges', slug: 'sum-of-subarray-ranges', difficulty: 'Medium' },
      { id: 581, title: 'Shortest Unsorted Continuous Subarray', slug: 'shortest-unsorted-continuous-subarray', difficulty: 'Medium' },
      { id: 1019, title: 'Next Greater Node In Linked List', slug: 'next-greater-node-in-linked-list', difficulty: 'Medium' },
      { id: 1944, title: 'Number of Visible People in a Queue', slug: 'number-of-visible-people-in-a-queue', difficulty: 'Hard' },
      { id: 84, title: 'Largest Rectangle in Histogram', slug: 'largest-rectangle-in-histogram', difficulty: 'Hard' },
      { id: 321, title: 'Create Maximum Number', slug: 'create-maximum-number', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Queues', emoji: '🧺', color: 'pink',
    questions: [
      { id: 933, title: 'Number of Recent Calls', slug: 'number-of-recent-calls', difficulty: 'Easy' },
      { id: 2073, title: 'Time Needed to Buy Tickets', slug: 'time-needed-to-buy-tickets', difficulty: 'Easy' },
      { id: 346, title: 'Moving Average from Data Stream', slug: 'moving-average-from-data-stream', difficulty: 'Easy' },
      { id: 950, title: 'Reveal Cards In Increasing Order', slug: 'reveal-cards-in-increasing-order', difficulty: 'Medium' },
      { id: 1429, title: 'First Unique Number', slug: 'first-unique-number', difficulty: 'Medium' },
      { id: 2327, title: 'Number of People Aware of a Secret', slug: 'number-of-people-aware-of-a-secret', difficulty: 'Medium' },
      { id: 1823, title: 'Find the Winner of the Circular Game', slug: 'find-the-winner-of-the-circular-game', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Monotonic Queue', emoji: '📬', color: 'slate',
    questions: [
      { id: 1696, title: 'Jump Game VI', slug: 'jump-game-vi', difficulty: 'Medium' },
      { id: 2762, title: 'Continuous Subarrays', slug: 'continuous-subarrays', difficulty: 'Medium' },
      { id: 1673, title: 'Find the Most Competitive Subsequence', slug: 'find-the-most-competitive-subsequence', difficulty: 'Medium' },
      { id: 3578, title: 'Count Partitions With Max-Min Difference at Most K', slug: 'count-partitions-with-max-min-difference-at-most-k', difficulty: 'Medium' },
      { id: 1438, title: 'Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit', slug: 'longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit', difficulty: 'Medium' },
      { id: 239, title: 'Sliding Window Maximum', slug: 'sliding-window-maximum', difficulty: 'Hard' },
      { id: 1499, title: 'Max Value of Equation', slug: 'max-value-of-equation', difficulty: 'Hard' },
      { id: 1425, title: 'Constrained Subsequence Sum', slug: 'constrained-subsequence-sum', difficulty: 'Hard' },
      { id: 862, title: 'Shortest Subarray with Sum at Least K', slug: 'shortest-subarray-with-sum-at-least-k', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Bucket Sort', emoji: '🪣', color: 'red',
    questions: [
      { id: 451, title: 'Sort Characters By Frequency', slug: 'sort-characters-by-frequency', difficulty: 'Medium' },
      { id: 692, title: 'Top K Frequent Words', slug: 'top-k-frequent-words', difficulty: 'Medium' },
      { id: 164, title: 'Maximum Gap', slug: 'maximum-gap', difficulty: 'Medium' },
      { id: 220, title: 'Contains Duplicate III', slug: 'contains-duplicate-iii', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Recursion', emoji: '🔁', color: 'indigo',
    questions: [
      { id: 21, title: 'Merge Two Sorted Lists', slug: 'merge-two-sorted-lists', difficulty: 'Easy' },
      { id: 50, title: 'Pow(x, n)', slug: 'powx-n', difficulty: 'Medium' },
      { id: 394, title: 'Decode String', slug: 'decode-string', difficulty: 'Medium' },
      { id: 761, title: 'Special Binary String', slug: 'special-binary-string', difficulty: 'Hard' },
      { id: 273, title: 'Integer to English Words', slug: 'integer-to-english-words', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Divide and Conquer', emoji: '✂️', color: 'cyan',
    questions: [
      { id: 1763, title: 'Longest Nice Substring', slug: 'longest-nice-substring', difficulty: 'Easy' },
      { id: 109, title: 'Convert Sorted List to Binary Search Tree', slug: 'convert-sorted-list-to-binary-search-tree', difficulty: 'Medium' },
      { id: 427, title: 'Construct Quad Tree', slug: 'construct-quad-tree', difficulty: 'Medium' },
      { id: 654, title: 'Maximum Binary Tree', slug: 'maximum-binary-tree', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Merge Sort', emoji: '🧩', color: 'sky',
    questions: [
      { id: 912, title: 'Sort an Array', slug: 'sort-an-array', difficulty: 'Medium' },
      { id: 148, title: 'Sort List', slug: 'sort-list', difficulty: 'Medium' },
      { id: 493, title: 'Reverse Pairs', slug: 'reverse-pairs', difficulty: 'Hard' },
      { id: 327, title: 'Count of Range Sum', slug: 'count-of-range-sum', difficulty: 'Hard' },
    ],
  },
  {
    name: 'QuickSort / QuickSelect', emoji: '⚙️', color: 'orange',
    questions: [
      { id: 75, title: 'Sort Colors', slug: 'sort-colors', difficulty: 'Medium' },
      { id: 215, title: 'Kth Largest Element in an Array', slug: 'kth-largest-element-in-an-array', difficulty: 'Medium' },
      { id: 1985, title: 'Find the Kth Largest Integer in the Array', slug: 'find-the-kth-largest-integer-in-the-array', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Binary Search', emoji: '🔍', color: 'violet',
    questions: [
      { id: 704, title: 'Binary Search', slug: 'binary-search', difficulty: 'Easy' },
      { id: 278, title: 'First Bad Version', slug: 'first-bad-version', difficulty: 'Easy' },
      { id: 367, title: 'Valid Perfect Square', slug: 'valid-perfect-square', difficulty: 'Easy' },
      { id: 35, title: 'Search Insert Position', slug: 'search-insert-position', difficulty: 'Easy' },
      { id: 374, title: 'Guess Number Higher or Lower', slug: 'guess-number-higher-or-lower', difficulty: 'Easy' },
      { id: 744, title: 'Find Smallest Letter Greater Than Target', slug: 'find-smallest-letter-greater-than-target', difficulty: 'Easy' },
      { id: 34, title: 'Find First and Last Position of Element in Sorted Array', slug: 'find-first-and-last-position-of-element-in-sorted-array', difficulty: 'Medium' },
      { id: 33, title: 'Search in Rotated Sorted Array', slug: 'search-in-rotated-sorted-array', difficulty: 'Medium' },
      { id: 81, title: 'Search in Rotated Sorted Array II', slug: 'search-in-rotated-sorted-array-ii', difficulty: 'Medium' },
      { id: 162, title: 'Find Peak Element', slug: 'find-peak-element', difficulty: 'Medium' },
      { id: 528, title: 'Random Pick with Weight', slug: 'random-pick-with-weight', difficulty: 'Medium' },
      { id: 658, title: 'Find K Closest Elements', slug: 'find-k-closest-elements', difficulty: 'Medium' },
      { id: 475, title: 'Heaters', slug: 'heaters', difficulty: 'Medium' },
      { id: 875, title: 'Koko Eating Bananas', slug: 'koko-eating-bananas', difficulty: 'Medium' },
      { id: 1011, title: 'Capacity To Ship Packages Within D Days', slug: 'capacity-to-ship-packages-within-d-days', difficulty: 'Medium' },
      { id: 1482, title: 'Minimum Number of Days to Make m Bouquets', slug: 'minimum-number-of-days-to-make-m-bouquets', difficulty: 'Medium' },
      { id: 153, title: 'Find Minimum in Rotated Sorted Array', slug: 'find-minimum-in-rotated-sorted-array', difficulty: 'Medium' },
      { id: 74, title: 'Search a 2D Matrix', slug: 'search-a-2d-matrix', difficulty: 'Medium' },
      { id: 240, title: 'Search a 2D Matrix II', slug: 'search-a-2d-matrix-ii', difficulty: 'Medium' },
      { id: 1552, title: 'Magnetic Force Between Two Balls', slug: 'magnetic-force-between-two-balls', difficulty: 'Medium' },
      { id: 1095, title: 'Find in Mountain Array', slug: 'find-in-mountain-array', difficulty: 'Hard' },
      { id: 410, title: 'Split Array Largest Sum', slug: 'split-array-largest-sum', difficulty: 'Hard' },
      { id: 4, title: 'Median of Two Sorted Arrays', slug: 'median-of-two-sorted-arrays', difficulty: 'Hard' },
      { id: 719, title: 'Find K-th Smallest Pair Distance', slug: 'find-k-th-smallest-pair-distance', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Backtracking', emoji: '🧠', color: 'teal',
    questions: [
      { id: 22, title: 'Generate Parentheses', slug: 'generate-parentheses', difficulty: 'Medium' },
      { id: 46, title: 'Permutations', slug: 'permutations', difficulty: 'Medium' },
      { id: 47, title: 'Permutations II', slug: 'permutations-ii', difficulty: 'Medium' },
      { id: 78, title: 'Subsets', slug: 'subsets', difficulty: 'Medium' },
      { id: 90, title: 'Subsets II', slug: 'subsets-ii', difficulty: 'Medium' },
      { id: 39, title: 'Combination Sum', slug: 'combination-sum', difficulty: 'Medium' },
      { id: 40, title: 'Combination Sum II', slug: 'combination-sum-ii', difficulty: 'Medium' },
      { id: 216, title: 'Combination Sum III', slug: 'combination-sum-iii', difficulty: 'Medium' },
      { id: 77, title: 'Combinations', slug: 'combinations', difficulty: 'Medium' },
      { id: 17, title: 'Letter Combinations of a Phone Number', slug: 'letter-combinations-of-a-phone-number', difficulty: 'Medium' },
      { id: 93, title: 'Restore IP Addresses', slug: 'restore-ip-addresses', difficulty: 'Medium' },
      { id: 131, title: 'Palindrome Partitioning', slug: 'palindrome-partitioning', difficulty: 'Medium' },
      { id: 980, title: 'Unique Paths III', slug: 'unique-paths-iii', difficulty: 'Hard' },
      { id: 301, title: 'Remove Invalid Parentheses', slug: 'remove-invalid-parentheses', difficulty: 'Hard' },
      { id: 51, title: 'N-Queens', slug: 'n-queens', difficulty: 'Hard' },
      { id: 37, title: 'Sudoku Solver', slug: 'sudoku-solver', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Tree Traversal - Level Order', emoji: '🌳', color: 'green',
    questions: [
      { id: 104, title: 'Maximum Depth of Binary Tree', slug: 'maximum-depth-of-binary-tree', difficulty: 'Easy' },
      { id: 637, title: 'Average of Levels in Binary Tree', slug: 'average-of-levels-in-binary-tree', difficulty: 'Easy' },
      { id: 102, title: 'Binary Tree Level Order Traversal', slug: 'binary-tree-level-order-traversal', difficulty: 'Medium' },
      { id: 199, title: 'Binary Tree Right Side View', slug: 'binary-tree-right-side-view', difficulty: 'Medium' },
      { id: 103, title: 'Binary Tree Zigzag Level Order Traversal', slug: 'binary-tree-zigzag-level-order-traversal', difficulty: 'Medium' },
      { id: 314, title: 'Binary Tree Vertical Order Traversal', slug: 'binary-tree-vertical-order-traversal', difficulty: 'Medium' },
      { id: 116, title: 'Populating Next Right Pointers in Each Node', slug: 'populating-next-right-pointers-in-each-node', difficulty: 'Medium' },
      { id: 117, title: 'Populating Next Right Pointers in Each Node II', slug: 'populating-next-right-pointers-in-each-node-ii', difficulty: 'Medium' },
      { id: 662, title: 'Maximum Width of Binary Tree', slug: 'maximum-width-of-binary-tree', difficulty: 'Medium' },
      { id: 958, title: 'Check Completeness of a Binary Tree', slug: 'check-completeness-of-a-binary-tree', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Tree Traversal - Pre Order', emoji: '🌲', color: 'fuchsia',
    questions: [
      { id: 144, title: 'Binary Tree Preorder Traversal', slug: 'binary-tree-preorder-traversal', difficulty: 'Easy' },
      { id: 100, title: 'Same Tree', slug: 'same-tree', difficulty: 'Easy' },
      { id: 101, title: 'Symmetric Tree', slug: 'symmetric-tree', difficulty: 'Easy' },
      { id: 404, title: 'Sum of Left Leaves', slug: 'sum-of-left-leaves', difficulty: 'Easy' },
      { id: 572, title: 'Subtree of Another Tree', slug: 'subtree-of-another-tree', difficulty: 'Easy' },
      { id: 257, title: 'Binary Tree Paths', slug: 'binary-tree-paths', difficulty: 'Easy' },
      { id: 108, title: 'Convert Sorted Array to Binary Search Tree', slug: 'convert-sorted-array-to-binary-search-tree', difficulty: 'Easy' },
      { id: 222, title: 'Count Complete Tree Nodes', slug: 'count-complete-tree-nodes', difficulty: 'Easy' },
      { id: 113, title: 'Path Sum II', slug: 'path-sum-ii', difficulty: 'Medium' },
      { id: 437, title: 'Path Sum III', slug: 'path-sum-iii', difficulty: 'Medium' },
      { id: 687, title: 'Longest Univalue Path', slug: 'longest-univalue-path', difficulty: 'Medium' },
      { id: 1026, title: 'Maximum Difference Between Node and Ancestor', slug: 'maximum-difference-between-node-and-ancestor', difficulty: 'Medium' },
      { id: 105, title: 'Construct Binary Tree from Preorder and Inorder Traversal', slug: 'construct-binary-tree-from-preorder-and-inorder-traversal', difficulty: 'Medium' },
      { id: 106, title: 'Construct Binary Tree from Inorder and Postorder Traversal', slug: 'construct-binary-tree-from-inorder-and-postorder-traversal', difficulty: 'Medium' },
      { id: 297, title: 'Serialize and Deserialize Binary Tree', slug: 'serialize-and-deserialize-binary-tree', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Tree Traversal - In Order', emoji: '🌴', color: 'rose',
    questions: [
      { id: 94, title: 'Binary Tree Inorder Traversal', slug: 'binary-tree-inorder-traversal', difficulty: 'Easy' },
      { id: 783, title: 'Minimum Distance Between BST Nodes', slug: 'minimum-distance-between-bst-nodes', difficulty: 'Easy' },
      { id: 530, title: 'Minimum Absolute Difference in BST', slug: 'minimum-absolute-difference-in-bst', difficulty: 'Easy' },
      { id: 98, title: 'Validate Binary Search Tree', slug: 'validate-binary-search-tree', difficulty: 'Medium' },
      { id: 230, title: 'Kth Smallest Element in a BST', slug: 'kth-smallest-element-in-a-bst', difficulty: 'Medium' },
      { id: 173, title: 'Binary Search Tree Iterator', slug: 'binary-search-tree-iterator', difficulty: 'Medium' },
      { id: 1382, title: 'Balance a Binary Search Tree', slug: 'balance-a-binary-search-tree', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Tree Traversal - Post-Order', emoji: '🌵', color: 'amber',
    questions: [
      { id: 145, title: 'Binary Tree Postorder Traversal', slug: 'binary-tree-postorder-traversal', difficulty: 'Easy' },
      { id: 226, title: 'Invert Binary Tree', slug: 'invert-binary-tree', difficulty: 'Easy' },
      { id: 110, title: 'Balanced Binary Tree', slug: 'balanced-binary-tree', difficulty: 'Easy' },
      { id: 543, title: 'Diameter of Binary Tree', slug: 'diameter-of-binary-tree', difficulty: 'Easy' },
      { id: 1448, title: 'Count Good Nodes in Binary Tree', slug: 'count-good-nodes-in-binary-tree', difficulty: 'Medium' },
      { id: 129, title: 'Sum Root to Leaf Numbers', slug: 'sum-root-to-leaf-numbers', difficulty: 'Medium' },
      { id: 1110, title: 'Delete Nodes And Return Forest', slug: 'delete-nodes-and-return-forest', difficulty: 'Medium' },
      { id: 236, title: 'Lowest Common Ancestor of a Binary Tree', slug: 'lowest-common-ancestor-of-a-binary-tree', difficulty: 'Medium' },
      { id: 652, title: 'Find Duplicate Subtrees', slug: 'find-duplicate-subtrees', difficulty: 'Medium' },
      { id: 114, title: 'Flatten Binary Tree to Linked List', slug: 'flatten-binary-tree-to-linked-list', difficulty: 'Medium' },
      { id: 979, title: 'Distribute Coins in Binary Tree', slug: 'distribute-coins-in-binary-tree', difficulty: 'Medium' },
      { id: 545, title: 'Boundary of Binary Tree', slug: 'boundary-of-binary-tree', difficulty: 'Medium' },
      { id: 2096, title: 'Step-By-Step Directions From a Binary Tree Node to Another', slug: 'step-by-step-directions-from-a-binary-tree-node-to-another', difficulty: 'Medium' },
      { id: 124, title: 'Binary Tree Maximum Path Sum', slug: 'binary-tree-maximum-path-sum', difficulty: 'Hard' },
    ],
  },
  {
    name: 'BST / Ordered Set', emoji: '🌿', color: 'blue',
    questions: [
      { id: 700, title: 'Search in a Binary Search Tree', slug: 'search-in-a-binary-search-tree', difficulty: 'Easy' },
      { id: 270, title: 'Closest Binary Search Tree Value', slug: 'closest-binary-search-tree-value', difficulty: 'Easy' },
      { id: 653, title: 'Two Sum IV - Input is a BST', slug: 'two-sum-iv-input-is-a-bst', difficulty: 'Easy' },
      { id: 938, title: 'Range Sum of BST', slug: 'range-sum-of-bst', difficulty: 'Easy' },
      { id: 285, title: 'Inorder Successor in BST', slug: 'inorder-successor-in-bst', difficulty: 'Medium' },
      { id: 510, title: 'Inorder Successor in BST II', slug: 'inorder-successor-in-bst-ii', difficulty: 'Medium' },
      { id: 701, title: 'Insert into a Binary Search Tree', slug: 'insert-into-a-binary-search-tree', difficulty: 'Medium' },
      { id: 450, title: 'Delete Node in a BST', slug: 'delete-node-in-a-bst', difficulty: 'Medium' },
      { id: 669, title: 'Trim a Binary Search Tree', slug: 'trim-a-binary-search-tree', difficulty: 'Medium' },
      { id: 235, title: 'Lowest Common Ancestor of a Binary Search Tree', slug: 'lowest-common-ancestor-of-a-binary-search-tree', difficulty: 'Medium' },
      { id: 333, title: 'Largest BST Subtree', slug: 'largest-bst-subtree', difficulty: 'Medium' },
      { id: 99, title: 'Recover Binary Search Tree', slug: 'recover-binary-search-tree', difficulty: 'Medium' },
      { id: 426, title: 'Convert Binary Search Tree to Sorted Doubly Linked List', slug: 'convert-binary-search-tree-to-sorted-doubly-linked-list', difficulty: 'Medium' },
      { id: 1008, title: 'Construct Binary Search Tree from Preorder Traversal', slug: 'construct-binary-search-tree-from-preorder-traversal', difficulty: 'Medium' },
      { id: 729, title: 'My Calendar I', slug: 'my-calendar-i', difficulty: 'Medium' },
      { id: 731, title: 'My Calendar II', slug: 'my-calendar-ii', difficulty: 'Medium' },
      { id: 2034, title: 'Stock Price Fluctuation ', slug: 'stock-price-fluctuation', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Tries', emoji: '🔠', color: 'purple',
    questions: [
      { id: 208, title: 'Implement Trie (Prefix Tree)', slug: 'implement-trie-prefix-tree', difficulty: 'Medium' },
      { id: 211, title: 'Design Add and Search Words Data Structure', slug: 'design-add-and-search-words-data-structure', difficulty: 'Medium' },
      { id: 1268, title: 'Search Suggestions System', slug: 'search-suggestions-system', difficulty: 'Medium' },
      { id: 720, title: 'Longest Word in Dictionary', slug: 'longest-word-in-dictionary', difficulty: 'Medium' },
      { id: 648, title: 'Replace Words', slug: 'replace-words', difficulty: 'Medium' },
      { id: 421, title: 'Maximum XOR of Two Numbers in an Array', slug: 'maximum-xor-of-two-numbers-in-an-array', difficulty: 'Medium' },
      { id: 1233, title: 'Remove Sub-Folders from the Filesystem', slug: 'remove-sub-folders-from-the-filesystem', difficulty: 'Medium' },
      { id: 3043, title: 'Find the Length of the Longest Common Prefix', slug: 'find-the-length-of-the-longest-common-prefix', difficulty: 'Medium' },
      { id: 2452, title: 'Words Within Two Edits of Dictionary', slug: 'words-within-two-edits-of-dictionary', difficulty: 'Medium' },
      { id: 212, title: 'Word Search II', slug: 'word-search-ii', difficulty: 'Hard' },
      { id: 1032, title: 'Stream of Characters', slug: 'stream-of-characters', difficulty: 'Hard' },
      { id: 472, title: 'Concatenated Words', slug: 'concatenated-words', difficulty: 'Hard' },
      { id: 425, title: 'Word Squares', slug: 'word-squares', difficulty: 'Hard' },
      { id: 336, title: 'Palindrome Pairs', slug: 'palindrome-pairs', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Heaps', emoji: '⛰️', color: 'emerald',
    questions: [
      { id: 1046, title: 'Last Stone Weight', slug: 'last-stone-weight', difficulty: 'Easy' },
      { id: 1167, title: 'Minimum Cost to Connect Sticks', slug: 'minimum-cost-to-connect-sticks', difficulty: 'Medium' },
      { id: 1642, title: 'Furthest Building You Can Reach', slug: 'furthest-building-you-can-reach', difficulty: 'Medium' },
      { id: 1834, title: 'Single-Threaded CPU', slug: 'single-threaded-cpu', difficulty: 'Medium' },
      { id: 1882, title: 'Process Tasks Using Servers', slug: 'process-tasks-using-servers', difficulty: 'Medium' },
      { id: 1383, title: 'Maximum Performance of a Team', slug: 'maximum-performance-of-a-team', difficulty: 'Hard' },
      { id: 1405, title: 'Longest Happy String', slug: 'longest-happy-string', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Two Heaps', emoji: '♨️', color: 'lime',
    questions: [
      { id: 295, title: 'Find Median from Data Stream', slug: 'find-median-from-data-stream', difficulty: 'Hard' },
      { id: 502, title: 'IPO', slug: 'ipo', difficulty: 'Hard' },
      { id: 480, title: 'Sliding Window Median', slug: 'sliding-window-median', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Top K Elements', emoji: '🏔️', color: 'yellow',
    questions: [
      { id: 703, title: 'Kth Largest Element in a Stream', slug: 'kth-largest-element-in-a-stream', difficulty: 'Easy' },
      { id: 347, title: 'Top K Frequent Elements', slug: 'top-k-frequent-elements', difficulty: 'Medium' },
      { id: 973, title: 'K Closest Points to Origin', slug: 'k-closest-points-to-origin', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Intervals', emoji: '🔝', color: 'pink',
    questions: [
      { id: 228, title: 'Summary Ranges', slug: 'summary-ranges', difficulty: 'Easy' },
      { id: 252, title: 'Meeting Rooms', slug: 'meeting-rooms', difficulty: 'Easy' },
      { id: 253, title: 'Meeting Rooms II', slug: 'meeting-rooms-ii', difficulty: 'Medium' },
      { id: 1229, title: 'Meeting Scheduler', slug: 'meeting-scheduler', difficulty: 'Medium' },
      { id: 986, title: 'Interval List Intersections', slug: 'interval-list-intersections', difficulty: 'Medium' },
      { id: 1094, title: 'Car Pooling', slug: 'car-pooling', difficulty: 'Medium' },
      { id: 56, title: 'Merge Intervals', slug: 'merge-intervals', difficulty: 'Medium' },
      { id: 57, title: 'Insert Interval', slug: 'insert-interval', difficulty: 'Medium' },
      { id: 1288, title: 'Remove Covered Intervals', slug: 'remove-covered-intervals', difficulty: 'Medium' },
      { id: 763, title: 'Partition Labels', slug: 'partition-labels', difficulty: 'Medium' },
      { id: 452, title: 'Minimum Number of Arrows to Burst Balloons', slug: 'minimum-number-of-arrows-to-burst-balloons', difficulty: 'Medium' },
      { id: 1353, title: 'Maximum Number of Events That Can Be Attended', slug: 'maximum-number-of-events-that-can-be-attended', difficulty: 'Medium' },
      { id: 435, title: 'Non-overlapping Intervals', slug: 'non-overlapping-intervals', difficulty: 'Medium' },
      { id: 2054, title: 'Two Best Non-Overlapping Events', slug: 'two-best-non-overlapping-events', difficulty: 'Medium' },
      { id: 2402, title: 'Meeting Rooms III', slug: 'meeting-rooms-iii', difficulty: 'Hard' },
    ],
  },
  {
    name: 'K-Way Merge', emoji: '📏', color: 'slate',
    questions: [
      { id: 373, title: 'Find K Pairs with Smallest Sums', slug: 'find-k-pairs-with-smallest-sums', difficulty: 'Medium' },
      { id: 378, title: 'Kth Smallest Element in a Sorted Matrix', slug: 'kth-smallest-element-in-a-sorted-matrix', difficulty: 'Medium' },
      { id: 23, title: 'Merge k Sorted Lists', slug: 'merge-k-sorted-lists', difficulty: 'Hard' },
      { id: 632, title: 'Smallest Range Covering Elements from K Lists', slug: 'smallest-range-covering-elements-from-k-lists', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Data Structure Design', emoji: '🔀', color: 'red',
    questions: [
      { id: 359, title: 'Logger Rate Limiter', slug: 'logger-rate-limiter', difficulty: 'Easy' },
      { id: 232, title: 'Implement Queue using Stacks', slug: 'implement-queue-using-stacks', difficulty: 'Easy' },
      { id: 225, title: 'Implement Stack using Queues', slug: 'implement-stack-using-queues', difficulty: 'Easy' },
      { id: 622, title: 'Design Circular Queue', slug: 'design-circular-queue', difficulty: 'Medium' },
      { id: 641, title: 'Design Circular Deque', slug: 'design-circular-deque', difficulty: 'Medium' },
      { id: 362, title: 'Design Hit Counter', slug: 'design-hit-counter', difficulty: 'Medium' },
      { id: 1472, title: 'Design Browser History', slug: 'design-browser-history', difficulty: 'Medium' },
      { id: 981, title: 'Time Based Key-Value Store', slug: 'time-based-key-value-store', difficulty: 'Medium' },
      { id: 271, title: 'Encode and Decode Strings', slug: 'encode-and-decode-strings', difficulty: 'Medium' },
      { id: 1146, title: 'Snapshot Array', slug: 'snapshot-array', difficulty: 'Medium' },
      { id: 355, title: 'Design Twitter', slug: 'design-twitter', difficulty: 'Medium' },
      { id: 146, title: 'LRU Cache', slug: 'lru-cache', difficulty: 'Medium' },
      { id: 380, title: 'Insert Delete GetRandom O(1)', slug: 'insert-delete-getrandom-o1', difficulty: 'Medium' },
      { id: 2353, title: 'Design a Food Rating System', slug: 'design-a-food-rating-system', difficulty: 'Medium' },
      { id: 460, title: 'LFU Cache', slug: 'lfu-cache', difficulty: 'Hard' },
      { id: 716, title: 'Max Stack', slug: 'max-stack', difficulty: 'Hard' },
      { id: 895, title: 'Maximum Frequency Stack', slug: 'maximum-frequency-stack', difficulty: 'Hard' },
      { id: 432, title: 'All O`one Data Structure', slug: 'all-oone-data-structure', difficulty: 'Hard' },
      { id: 715, title: 'Range Module', slug: 'range-module', difficulty: 'Hard' },
      { id: 642, title: 'Design Search Autocomplete System', slug: 'design-search-autocomplete-system', difficulty: 'Hard' },
      { id: 588, title: 'Design In-Memory File System', slug: 'design-in-memory-file-system', difficulty: 'Hard' },
      { id: 2296, title: 'Design a Text Editor', slug: 'design-a-text-editor', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Greedy', emoji: '🏗️', color: 'indigo',
    questions: [
      { id: 455, title: 'Assign Cookies', slug: 'assign-cookies', difficulty: 'Easy' },
      { id: 3074, title: 'Apple Redistribution into Boxes', slug: 'apple-redistribution-into-boxes', difficulty: 'Easy' },
      { id: 55, title: 'Jump Game', slug: 'jump-game', difficulty: 'Medium' },
      { id: 45, title: 'Jump Game II', slug: 'jump-game-ii', difficulty: 'Medium' },
      { id: 1871, title: 'Jump Game VII', slug: 'jump-game-vii', difficulty: 'Medium' },
      { id: 921, title: 'Minimum Add to Make Parentheses Valid', slug: 'minimum-add-to-make-parentheses-valid', difficulty: 'Medium' },
      { id: 134, title: 'Gas Station', slug: 'gas-station', difficulty: 'Medium' },
      { id: 621, title: 'Task Scheduler', slug: 'task-scheduler', difficulty: 'Medium' },
      { id: 670, title: 'Maximum Swap', slug: 'maximum-swap', difficulty: 'Medium' },
      { id: 406, title: 'Queue Reconstruction by Height', slug: 'queue-reconstruction-by-height', difficulty: 'Medium' },
      { id: 1717, title: 'Maximum Score From Removing Substrings', slug: 'maximum-score-from-removing-substrings', difficulty: 'Medium' },
      { id: 1488, title: 'Avoid Flood in The City', slug: 'avoid-flood-in-the-city', difficulty: 'Medium' },
      { id: 1975, title: 'Maximum Matrix Sum', slug: 'maximum-matrix-sum', difficulty: 'Medium' },
      { id: 826, title: 'Most Profit Assigning Work', slug: 'most-profit-assigning-work', difficulty: 'Medium' },
      { id: 857, title: 'Minimum Cost to Hire K Workers', slug: 'minimum-cost-to-hire-k-workers', difficulty: 'Hard' },
      { id: 135, title: 'Candy', slug: 'candy', difficulty: 'Hard' },
      { id: 871, title: 'Minimum Number of Refueling Stops', slug: 'minimum-number-of-refueling-stops', difficulty: 'Hard' },
      { id: 757, title: 'Set Intersection Size At Least Two', slug: 'set-intersection-size-at-least-two', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Depth First Search (DFS)', emoji: '🤝', color: 'cyan',
    questions: [
      { id: 733, title: 'Flood Fill', slug: 'flood-fill', difficulty: 'Easy' },
      { id: 200, title: 'Number of Islands', slug: 'number-of-islands', difficulty: 'Medium' },
      { id: 694, title: 'Number of Distinct Islands', slug: 'number-of-distinct-islands', difficulty: 'Medium' },
      { id: 79, title: 'Word Search', slug: 'word-search', difficulty: 'Medium' },
      { id: 1376, title: 'Time Needed to Inform All Employees', slug: 'time-needed-to-inform-all-employees', difficulty: 'Medium' },
      { id: 797, title: 'All Paths From Source to Target', slug: 'all-paths-from-source-to-target', difficulty: 'Medium' },
      { id: 133, title: 'Clone Graph', slug: 'clone-graph', difficulty: 'Medium' },
      { id: 785, title: 'Is Graph Bipartite?', slug: 'is-graph-bipartite', difficulty: 'Medium' },
      { id: 863, title: 'All Nodes Distance K in Binary Tree', slug: 'all-nodes-distance-k-in-binary-tree', difficulty: 'Medium' },
      { id: 690, title: 'Employee Importance', slug: 'employee-importance', difficulty: 'Medium' },
      { id: 130, title: 'Surrounded Regions', slug: 'surrounded-regions', difficulty: 'Medium' },
      { id: 417, title: 'Pacific Atlantic Water Flow', slug: 'pacific-atlantic-water-flow', difficulty: 'Medium' },
      { id: 1020, title: 'Number of Enclaves', slug: 'number-of-enclaves', difficulty: 'Medium' },
      { id: 827, title: 'Making A Large Island', slug: 'making-a-large-island', difficulty: 'Hard' },
      { id: 1192, title: 'Critical Connections in a Network', slug: 'critical-connections-in-a-network', difficulty: 'Hard' },
      { id: 2246, title: 'Longest Path With Different Adjacent Characters', slug: 'longest-path-with-different-adjacent-characters', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Breadth First Search (BFS)', emoji: '🌊', color: 'sky',
    questions: [
      { id: 994, title: 'Rotting Oranges', slug: 'rotting-oranges', difficulty: 'Medium' },
      { id: 542, title: '01 Matrix', slug: '01-matrix', difficulty: 'Medium' },
      { id: 752, title: 'Open the Lock', slug: 'open-the-lock', difficulty: 'Medium' },
      { id: 909, title: 'Snakes and Ladders', slug: 'snakes-and-ladders', difficulty: 'Medium' },
      { id: 433, title: 'Minimum Genetic Mutation', slug: 'minimum-genetic-mutation', difficulty: 'Medium' },
      { id: 286, title: 'Walls and Gates', slug: 'walls-and-gates', difficulty: 'Medium' },
      { id: 1197, title: 'Minimum Knight Moves', slug: 'minimum-knight-moves', difficulty: 'Medium' },
      { id: 1091, title: 'Shortest Path in Binary Matrix', slug: 'shortest-path-in-binary-matrix', difficulty: 'Medium' },
      { id: 1102, title: 'Path With Maximum Minimum Value', slug: 'path-with-maximum-minimum-value', difficulty: 'Medium' },
      { id: 1293, title: 'Shortest Path in a Grid with Obstacles Elimination', slug: 'shortest-path-in-a-grid-with-obstacles-elimination', difficulty: 'Hard' },
      { id: 815, title: 'Bus Routes', slug: 'bus-routes', difficulty: 'Hard' },
      { id: 127, title: 'Word Ladder', slug: 'word-ladder', difficulty: 'Hard' },
      { id: 2290, title: 'Minimum Obstacle Removal to Reach Corner', slug: 'minimum-obstacle-removal-to-reach-corner', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Topological Sort', emoji: '🌐', color: 'orange',
    questions: [
      { id: 210, title: 'Course Schedule II', slug: 'course-schedule-ii', difficulty: 'Medium' },
      { id: 1462, title: 'Course Schedule IV', slug: 'course-schedule-iv', difficulty: 'Medium' },
      { id: 1136, title: 'Parallel Courses', slug: 'parallel-courses', difficulty: 'Medium' },
      { id: 802, title: 'Find Eventual Safe States', slug: 'find-eventual-safe-states', difficulty: 'Medium' },
      { id: 310, title: 'Minimum Height Trees', slug: 'minimum-height-trees', difficulty: 'Medium' },
      { id: 2115, title: 'Find All Possible Recipes from Given Supplies', slug: 'find-all-possible-recipes-from-given-supplies', difficulty: 'Medium' },
      { id: 1203, title: 'Sort Items by Groups Respecting Dependencies', slug: 'sort-items-by-groups-respecting-dependencies', difficulty: 'Hard' },
      { id: 269, title: 'Alien Dictionary', slug: 'alien-dictionary', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Union Find', emoji: '🧭', color: 'violet',
    questions: [
      { id: 323, title: 'Number of Connected Components in an Undirected Graph', slug: 'number-of-connected-components-in-an-undirected-graph', difficulty: 'Medium' },
      { id: 547, title: 'Number of Provinces', slug: 'number-of-provinces', difficulty: 'Medium' },
      { id: 684, title: 'Redundant Connection', slug: 'redundant-connection', difficulty: 'Medium' },
      { id: 261, title: 'Graph Valid Tree', slug: 'graph-valid-tree', difficulty: 'Medium' },
      { id: 721, title: 'Accounts Merge', slug: 'accounts-merge', difficulty: 'Medium' },
      { id: 399, title: 'Evaluate Division', slug: 'evaluate-division', difficulty: 'Medium' },
      { id: 947, title: 'Most Stones Removed with Same Row or Column', slug: 'most-stones-removed-with-same-row-or-column', difficulty: 'Medium' },
      { id: 924, title: 'Minimize Malware Spread', slug: 'minimize-malware-spread', difficulty: 'Hard' },
      { id: 305, title: 'Number of Islands II', slug: 'number-of-islands-ii', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Minimum Spanning Tree', emoji: '🔗', color: 'teal',
    questions: [
      { id: 1584, title: 'Min Cost to Connect All Points', slug: 'min-cost-to-connect-all-points', difficulty: 'Medium' },
      { id: 1135, title: 'Connecting Cities With Minimum Cost', slug: 'connecting-cities-with-minimum-cost', difficulty: 'Medium' },
      { id: 1168, title: 'Optimize Water Distribution in a Village', slug: 'optimize-water-distribution-in-a-village', difficulty: 'Hard' },
      { id: 1489, title: 'Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree', slug: 'find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree', difficulty: 'Hard' },
      { id: 3600, title: 'Maximize Spanning Tree Stability with Upgrades', slug: 'maximize-spanning-tree-stability-with-upgrades', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Shortest Path', emoji: '🛤️', color: 'green',
    questions: [
      { id: 743, title: 'Network Delay Time', slug: 'network-delay-time', difficulty: 'Medium' },
      { id: 787, title: 'Cheapest Flights Within K Stops', slug: 'cheapest-flights-within-k-stops', difficulty: 'Medium' },
      { id: 1514, title: 'Path with Maximum Probability', slug: 'path-with-maximum-probability', difficulty: 'Medium' },
      { id: 1631, title: 'Path With Minimum Effort', slug: 'path-with-minimum-effort', difficulty: 'Medium' },
      { id: 505, title: 'The Maze II', slug: 'the-maze-ii', difficulty: 'Medium' },
      { id: 2976, title: 'Minimum Cost to Convert String I', slug: 'minimum-cost-to-convert-string-i', difficulty: 'Medium' },
      { id: 3650, title: 'Minimum Cost Path with Edge Reversals', slug: 'minimum-cost-path-with-edge-reversals', difficulty: 'Medium' },
      { id: 3341, title: 'Find Minimum Time to Reach Last Room I', slug: 'find-minimum-time-to-reach-last-room-i', difficulty: 'Medium' },
      { id: 778, title: 'Swim in Rising Water', slug: 'swim-in-rising-water', difficulty: 'Hard' },
      { id: 1368, title: 'Minimum Cost to Make at Least One Valid Path in a Grid', slug: 'minimum-cost-to-make-at-least-one-valid-path-in-a-grid', difficulty: 'Hard' },
      { id: 2203, title: 'Minimum Weighted Subgraph With the Required Paths', slug: 'minimum-weighted-subgraph-with-the-required-paths', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Eulerian Circuit', emoji: '🚗', color: 'fuchsia',
    questions: [
      { id: 332, title: 'Reconstruct Itinerary', slug: 'reconstruct-itinerary', difficulty: 'Hard' },
      { id: 753, title: 'Cracking the Safe', slug: 'cracking-the-safe', difficulty: 'Hard' },
      { id: 2097, title: 'Valid Arrangement of Pairs', slug: 'valid-arrangement-of-pairs', difficulty: 'Hard' },
    ],
  },
  {
    name: '1-D DP', emoji: '🔵', color: 'rose',
    questions: [
      { id: 509, title: 'Fibonacci Number', slug: 'fibonacci-number', difficulty: 'Easy' },
      { id: 70, title: 'Climbing Stairs', slug: 'climbing-stairs', difficulty: 'Easy' },
      { id: 746, title: 'Min Cost Climbing Stairs', slug: 'min-cost-climbing-stairs', difficulty: 'Easy' },
      { id: 198, title: 'House Robber', slug: 'house-robber', difficulty: 'Medium' },
      { id: 213, title: 'House Robber II', slug: 'house-robber-ii', difficulty: 'Medium' },
      { id: 646, title: 'Maximum Length of Pair Chain', slug: 'maximum-length-of-pair-chain', difficulty: 'Medium' },
      { id: 740, title: 'Delete and Earn', slug: 'delete-and-earn', difficulty: 'Medium' },
      { id: 343, title: 'Integer Break', slug: 'integer-break', difficulty: 'Medium' },
      { id: 1262, title: 'Greatest Sum Divisible by Three', slug: 'greatest-sum-divisible-by-three', difficulty: 'Medium' },
      { id: 1411, title: 'Number of Ways to Paint N × 3 Grid', slug: 'number-of-ways-to-paint-n-3-grid', difficulty: 'Hard' },
    ],
  },
  {
    name: '0/1 Knapsack', emoji: '🚦', color: 'amber',
    questions: [
      { id: 416, title: 'Partition Equal Subset Sum', slug: 'partition-equal-subset-sum', difficulty: 'Medium' },
      { id: 494, title: 'Target Sum', slug: 'target-sum', difficulty: 'Medium' },
      { id: 1049, title: 'Last Stone Weight II', slug: 'last-stone-weight-ii', difficulty: 'Medium' },
      { id: 474, title: 'Ones and Zeroes', slug: 'ones-and-zeroes', difficulty: 'Medium' },
      { id: 879, title: 'Profitable Schemes', slug: 'profitable-schemes', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Unbounded Knapsack', emoji: '🛣️', color: 'blue',
    questions: [
      { id: 322, title: 'Coin Change', slug: 'coin-change', difficulty: 'Medium' },
      { id: 518, title: 'Coin Change II', slug: 'coin-change-ii', difficulty: 'Medium' },
      { id: 279, title: 'Perfect Squares', slug: 'perfect-squares', difficulty: 'Medium' },
      { id: 983, title: 'Minimum Cost For Tickets', slug: 'minimum-cost-for-tickets', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Longest Increasing Subsequence (LIS)', emoji: '💰', color: 'purple',
    questions: [
      { id: 300, title: 'Longest Increasing Subsequence', slug: 'longest-increasing-subsequence', difficulty: 'Medium' },
      { id: 673, title: 'Number of Longest Increasing Subsequence', slug: 'number-of-longest-increasing-subsequence', difficulty: 'Medium' },
      { id: 1048, title: 'Longest String Chain', slug: 'longest-string-chain', difficulty: 'Medium' },
      { id: 1027, title: 'Longest Arithmetic Subsequence', slug: 'longest-arithmetic-subsequence', difficulty: 'Medium' },
      { id: 354, title: 'Russian Doll Envelopes', slug: 'russian-doll-envelopes', difficulty: 'Hard' },
    ],
  },
  {
    name: '2D Grid DP', emoji: '🎒', color: 'emerald',
    questions: [
      { id: 118, title: 'Pascal\'s Triangle', slug: 'pascals-triangle', difficulty: 'Easy' },
      { id: 62, title: 'Unique Paths', slug: 'unique-paths', difficulty: 'Medium' },
      { id: 63, title: 'Unique Paths II', slug: 'unique-paths-ii', difficulty: 'Medium' },
      { id: 64, title: 'Minimum Path Sum', slug: 'minimum-path-sum', difficulty: 'Medium' },
      { id: 120, title: 'Triangle', slug: 'triangle', difficulty: 'Medium' },
      { id: 221, title: 'Maximal Square', slug: 'maximal-square', difficulty: 'Medium' },
      { id: 1277, title: 'Count Square Submatrices with All Ones', slug: 'count-square-submatrices-with-all-ones', difficulty: 'Medium' },
      { id: 1937, title: 'Maximum Number of Points with Cost', slug: 'maximum-number-of-points-with-cost', difficulty: 'Medium' },
      { id: 256, title: 'Paint House', slug: 'paint-house', difficulty: 'Medium' },
      { id: 931, title: 'Minimum Falling Path Sum', slug: 'minimum-falling-path-sum', difficulty: 'Medium' },
      { id: 1235, title: 'Maximum Profit in Job Scheduling', slug: 'maximum-profit-in-job-scheduling', difficulty: 'Hard' },
      { id: 312, title: 'Burst Balloons', slug: 'burst-balloons', difficulty: 'Hard' },
      { id: 546, title: 'Remove Boxes', slug: 'remove-boxes', difficulty: 'Hard' },
      { id: 85, title: 'Maximal Rectangle', slug: 'maximal-rectangle', difficulty: 'Hard' },
      { id: 741, title: 'Cherry Pickup', slug: 'cherry-pickup', difficulty: 'Hard' },
      { id: 174, title: 'Dungeon Game', slug: 'dungeon-game', difficulty: 'Hard' },
      { id: 329, title: 'Longest Increasing Path in a Matrix', slug: 'longest-increasing-path-in-a-matrix', difficulty: 'Hard' },
      { id: 1931, title: 'Painting a Grid With Three Different Colors', slug: 'painting-a-grid-with-three-different-colors', difficulty: 'Hard' },
      { id: 3651, title: 'Minimum Cost Path with Teleportations', slug: 'minimum-cost-path-with-teleportations', difficulty: 'Hard' },
      { id: 403, title: 'Frog Jump', slug: 'frog-jump', difficulty: 'Hard' },
      { id: 465, title: 'Optimal Account Balancing', slug: 'optimal-account-balancing', difficulty: 'Hard' },
      { id: 1335, title: 'Minimum Difficulty of a Job Schedule', slug: 'minimum-difficulty-of-a-job-schedule', difficulty: 'Hard' },
      { id: 1547, title: 'Minimum Cost to Cut a Stick', slug: 'minimum-cost-to-cut-a-stick', difficulty: 'Hard' },
    ],
  },
  {
    name: 'String DP', emoji: '🧳', color: 'lime',
    questions: [
      { id: 1143, title: 'Longest Common Subsequence', slug: 'longest-common-subsequence', difficulty: 'Medium' },
      { id: 516, title: 'Longest Palindromic Subsequence', slug: 'longest-palindromic-subsequence', difficulty: 'Medium' },
      { id: 72, title: 'Edit Distance', slug: 'edit-distance', difficulty: 'Medium' },
      { id: 91, title: 'Decode Ways', slug: 'decode-ways', difficulty: 'Medium' },
      { id: 139, title: 'Word Break', slug: 'word-break', difficulty: 'Medium' },
      { id: 97, title: 'Interleaving String', slug: 'interleaving-string', difficulty: 'Medium' },
      { id: 1653, title: 'Minimum Deletions to Make String Balanced', slug: 'minimum-deletions-to-make-string-balanced', difficulty: 'Medium' },
      { id: 140, title: 'Word Break II', slug: 'word-break-ii', difficulty: 'Hard' },
      { id: 44, title: 'Wildcard Matching', slug: 'wildcard-matching', difficulty: 'Hard' },
      { id: 10, title: 'Regular Expression Matching', slug: 'regular-expression-matching', difficulty: 'Hard' },
      { id: 115, title: 'Distinct Subsequences', slug: 'distinct-subsequences', difficulty: 'Hard' },
      { id: 132, title: 'Palindrome Partitioning II', slug: 'palindrome-partitioning-ii', difficulty: 'Hard' },
      { id: 664, title: 'Strange Printer', slug: 'strange-printer', difficulty: 'Hard' },
      { id: 1092, title: 'Shortest Common Supersequence', slug: 'shortest-common-supersequence', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Tree / Graph DP', emoji: '📊', color: 'yellow',
    questions: [
      { id: 337, title: 'House Robber III', slug: 'house-robber-iii', difficulty: 'Medium' },
      { id: 95, title: 'Unique Binary Search Trees II', slug: 'unique-binary-search-trees-ii', difficulty: 'Medium' },
      { id: 1976, title: 'Number of Ways to Arrive at Destination', slug: 'number-of-ways-to-arrive-at-destination', difficulty: 'Medium' },
      { id: 968, title: 'Binary Tree Cameras', slug: 'binary-tree-cameras', difficulty: 'Hard' },
      { id: 834, title: 'Sum of Distances in Tree', slug: 'sum-of-distances-in-tree', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Bitmask DP', emoji: '🗺️', color: 'pink',
    questions: [
      { id: 1066, title: 'Campus Bikes II', slug: 'campus-bikes-ii', difficulty: 'Medium' },
      { id: 698, title: 'Partition to K Equal Sum Subsets', slug: 'partition-to-k-equal-sum-subsets', difficulty: 'Medium' },
      { id: 1986, title: 'Minimum Number of Work Sessions to Finish the Tasks', slug: 'minimum-number-of-work-sessions-to-finish-the-tasks', difficulty: 'Medium' },
      { id: 2305, title: 'Fair Distribution of Cookies', slug: 'fair-distribution-of-cookies', difficulty: 'Medium' },
      { id: 847, title: 'Shortest Path Visiting All Nodes', slug: 'shortest-path-visiting-all-nodes', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Digit DP', emoji: '📝', color: 'slate',
    questions: [
      { id: 357, title: 'Count Numbers with Unique Digits', slug: 'count-numbers-with-unique-digits', difficulty: 'Medium' },
      { id: 233, title: 'Number of Digit One', slug: 'number-of-digit-one', difficulty: 'Hard' },
      { id: 902, title: 'Numbers At Most N Given Digit Set', slug: 'numbers-at-most-n-given-digit-set', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Probability DP', emoji: '🌱', color: 'red',
    questions: [
      { id: 688, title: 'Knight Probability in Chessboard', slug: 'knight-probability-in-chessboard', difficulty: 'Medium' },
      { id: 808, title: 'Soup Servings', slug: 'soup-servings', difficulty: 'Medium' },
      { id: 837, title: 'New 21 Game', slug: 'new-21-game', difficulty: 'Medium' },
    ],
  },
  {
    name: 'State Machine DP', emoji: '🎲', color: 'indigo',
    questions: [
      { id: 309, title: 'Best Time to Buy and Sell Stock with Cooldown', slug: 'best-time-to-buy-and-sell-stock-with-cooldown', difficulty: 'Medium' },
      { id: 714, title: 'Best Time to Buy and Sell Stock with Transaction Fee', slug: 'best-time-to-buy-and-sell-stock-with-transaction-fee', difficulty: 'Medium' },
      { id: 123, title: 'Best Time to Buy and Sell Stock III', slug: 'best-time-to-buy-and-sell-stock-iii', difficulty: 'Hard' },
      { id: 188, title: 'Best Time to Buy and Sell Stock IV', slug: 'best-time-to-buy-and-sell-stock-iv', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Maths / Geometry', emoji: '🎰', color: 'cyan',
    questions: [
      { id: 9, title: 'Palindrome Number', slug: 'palindrome-number', difficulty: 'Easy' },
      { id: 66, title: 'Plus One', slug: 'plus-one', difficulty: 'Easy' },
      { id: 13, title: 'Roman to Integer', slug: 'roman-to-integer', difficulty: 'Easy' },
      { id: 168, title: 'Excel Sheet Column Title', slug: 'excel-sheet-column-title', difficulty: 'Easy' },
      { id: 1071, title: 'Greatest Common Divisor of Strings', slug: 'greatest-common-divisor-of-strings', difficulty: 'Easy' },
      { id: 263, title: 'Ugly Number', slug: 'ugly-number', difficulty: 'Easy' },
      { id: 264, title: 'Ugly Number II', slug: 'ugly-number-ii', difficulty: 'Medium' },
      { id: 7, title: 'Reverse Integer', slug: 'reverse-integer', difficulty: 'Medium' },
      { id: 43, title: 'Multiply Strings', slug: 'multiply-strings', difficulty: 'Medium' },
      { id: 287, title: 'Find the Duplicate Number', slug: 'find-the-duplicate-number', difficulty: 'Medium' },
      { id: 1922, title: 'Count Good Numbers', slug: 'count-good-numbers', difficulty: 'Medium' },
      { id: 204, title: 'Count Primes', slug: 'count-primes', difficulty: 'Medium' },
      { id: 172, title: 'Factorial Trailing Zeroes', slug: 'factorial-trailing-zeroes', difficulty: 'Medium' },
      { id: 611, title: 'Valid Triangle Number', slug: 'valid-triangle-number', difficulty: 'Medium' },
      { id: 593, title: 'Valid Square', slug: 'valid-square', difficulty: 'Medium' },
      { id: 939, title: 'Minimum Area Rectangle', slug: 'minimum-area-rectangle', difficulty: 'Medium' },
      { id: 963, title: 'Minimum Area Rectangle II', slug: 'minimum-area-rectangle-ii', difficulty: 'Medium' },
      { id: 149, title: 'Max Points on a Line', slug: 'max-points-on-a-line', difficulty: 'Hard' },
    ],
  },
  {
    name: 'String Matching', emoji: '🎮', color: 'sky',
    questions: [
      { id: 459, title: 'Repeated Substring Pattern', slug: 'repeated-substring-pattern', difficulty: 'Easy' },
      { id: 686, title: 'Repeated String Match', slug: 'repeated-string-match', difficulty: 'Medium' },
      { id: 1698, title: 'Number of Distinct Substrings in a String', slug: 'number-of-distinct-substrings-in-a-string', difficulty: 'Medium' },
      { id: 1392, title: 'Longest Happy Prefix', slug: 'longest-happy-prefix', difficulty: 'Hard' },
      { id: 214, title: 'Shortest Palindrome', slug: 'shortest-palindrome', difficulty: 'Hard' },
      { id: 1044, title: 'Longest Duplicate Substring', slug: 'longest-duplicate-substring', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Binary Indexed Tree / Segment Tree', emoji: '🚥', color: 'orange',
    questions: [
      { id: 307, title: 'Range Sum Query - Mutable', slug: 'range-sum-query-mutable', difficulty: 'Medium' },
      { id: 308, title: 'Range Sum Query 2D - Mutable', slug: 'range-sum-query-2d-mutable', difficulty: 'Medium' },
      { id: 315, title: 'Count of Smaller Numbers After Self', slug: 'count-of-smaller-numbers-after-self', difficulty: 'Hard' },
      { id: 699, title: 'Falling Squares', slug: 'falling-squares', difficulty: 'Hard' },
      { id: 3161, title: 'Block Placement Queries', slug: 'block-placement-queries', difficulty: 'Hard' },
      { id: 3721, title: 'Longest Balanced Subarray II', slug: 'longest-balanced-subarray-ii', difficulty: 'Hard' },
      { id: 2426, title: 'Number of Pairs Satisfying Inequality', slug: 'number-of-pairs-satisfying-inequality', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Line Sweep', emoji: '📐', color: 'violet',
    questions: [
      { id: 759, title: 'Employee Free Time', slug: 'employee-free-time', difficulty: 'Hard' },
      { id: 1851, title: 'Minimum Interval to Include Each Query', slug: 'minimum-interval-to-include-each-query', difficulty: 'Hard' },
      { id: 218, title: 'The Skyline Problem', slug: 'the-skyline-problem', difficulty: 'Hard' },
      { id: 850, title: 'Rectangle Area II', slug: 'rectangle-area-ii', difficulty: 'Hard' },
      { id: 391, title: 'Perfect Rectangle', slug: 'perfect-rectangle', difficulty: 'Hard' },
    ],
  },
]