export type NC250Question = {
  id: number
  title: string
  slug: string
  difficulty: 'Easy' | 'Medium' | 'Hard'
  acceptance: number
}

export type NC250Category = {
  name: string
  emoji: string
  color: string
  questions: NC250Question[]
}

export const NEETCODE_250: NC250Category[] = [
  {
    name: 'Arrays & Hashing', emoji: '📦', color: 'indigo',
    questions: [
      { id: 1929, title: 'Concatenation of Array', slug: 'concatenation-of-array', difficulty: 'Easy', acceptance: 93.5 },
      { id: 217,  title: 'Contains Duplicate', slug: 'contains-duplicate', difficulty: 'Easy', acceptance: 64.3 },
      { id: 242,  title: 'Valid Anagram', slug: 'valid-anagram', difficulty: 'Easy', acceptance: 68.0 },
      { id: 1,    title: 'Two Sum', slug: 'two-sum', difficulty: 'Easy', acceptance: 57.4 },
      { id: 14,   title: 'Longest Common Prefix', slug: 'longest-common-prefix', difficulty: 'Easy', acceptance: 45.1 },
      { id: 49,   title: 'Group Anagrams', slug: 'group-anagrams', difficulty: 'Medium', acceptance: 72.5 },
      { id: 27,   title: 'Remove Element', slug: 'remove-element', difficulty: 'Easy', acceptance: 58.1 },
      { id: 169,  title: 'Majority Element', slug: 'majority-element', difficulty: 'Easy', acceptance: 66.8 },
      { id: 705,  title: 'Design HashSet', slug: 'design-hashset', difficulty: 'Easy', acceptance: 72.1 },
      { id: 706,  title: 'Design HashMap', slug: 'design-hashmap', difficulty: 'Easy', acceptance: 68.2 },
      { id: 912,  title: 'Sort an Array', slug: 'sort-an-array', difficulty: 'Medium', acceptance: 64.7 },
      { id: 75,   title: 'Sort Colors', slug: 'sort-colors', difficulty: 'Medium', acceptance: 63.7 },
      { id: 347,  title: 'Top K Frequent Elements', slug: 'top-k-frequent-elements', difficulty: 'Medium', acceptance: 66.3 },
      { id: 271,  title: 'Encode and Decode Strings', slug: 'encode-and-decode-strings', difficulty: 'Medium', acceptance: 51.5 },
      { id: 303,  title: 'Range Sum Query - Immutable', slug: 'range-sum-query-immutable', difficulty: 'Easy', acceptance: 63.1 },
      { id: 238,  title: 'Product of Array Except Self', slug: 'product-of-array-except-self', difficulty: 'Medium', acceptance: 68.8 },
      { id: 36,   title: 'Valid Sudoku', slug: 'valid-sudoku', difficulty: 'Medium', acceptance: 64.4 },
      { id: 128,  title: 'Longest Consecutive Sequence', slug: 'longest-consecutive-sequence', difficulty: 'Medium', acceptance: 47.1 },
      { id: 122,  title: 'Best Time to Buy and Sell Stock II', slug: 'best-time-to-buy-and-sell-stock-ii', difficulty: 'Medium', acceptance: 68.4 },
      { id: 229,  title: 'Majority Element II', slug: 'majority-element-ii', difficulty: 'Medium', acceptance: 52.3 },
      { id: 560,  title: 'Subarray Sum Equals K', slug: 'subarray-sum-equals-k', difficulty: 'Medium', acceptance: 46.5 },
      { id: 41,   title: 'First Missing Positive', slug: 'first-missing-positive', difficulty: 'Hard', acceptance: 40.0 },
    ],
  },
  {
    name: 'Two Pointers', emoji: '👆', color: 'cyan',
    questions: [
      { id: 344,  title: 'Reverse String', slug: 'reverse-string', difficulty: 'Easy', acceptance: 78.0 },
      { id: 125,  title: 'Valid Palindrome', slug: 'valid-palindrome', difficulty: 'Easy', acceptance: 53.2 },
      { id: 680,  title: 'Valid Palindrome II', slug: 'valid-palindrome-ii', difficulty: 'Easy', acceptance: 40.8 },
      { id: 1768, title: 'Merge Strings Alternately', slug: 'merge-strings-alternately', difficulty: 'Easy', acceptance: 82.5 },
      { id: 88,   title: 'Merge Sorted Array', slug: 'merge-sorted-array', difficulty: 'Easy', acceptance: 51.8 },
      { id: 26,   title: 'Remove Duplicates from Sorted Array', slug: 'remove-duplicates-from-sorted-array', difficulty: 'Easy', acceptance: 56.1 },
      { id: 167,  title: 'Two Sum II - Input Array Is Sorted', slug: 'two-sum-ii-input-array-is-sorted', difficulty: 'Medium', acceptance: 65.0 },
      { id: 15,   title: '3Sum', slug: '3sum', difficulty: 'Medium', acceptance: 39.0 },
      { id: 18,   title: '4Sum', slug: '4sum', difficulty: 'Medium', acceptance: 38.2 },
      { id: 189,  title: 'Rotate Array', slug: 'rotate-array', difficulty: 'Medium', acceptance: 43.5 },
      { id: 11,   title: 'Container With Most Water', slug: 'container-with-most-water', difficulty: 'Medium', acceptance: 59.9 },
      { id: 881,  title: 'Boats to Save People', slug: 'boats-to-save-people', difficulty: 'Medium', acceptance: 55.8 },
      { id: 42,   title: 'Trapping Rain Water', slug: 'trapping-rain-water', difficulty: 'Hard', acceptance: 67.2 },
    ],
  },
  {
    name: 'Sliding Window', emoji: '🪟', color: 'sky',
    questions: [
      { id: 219,  title: 'Contains Duplicate II', slug: 'contains-duplicate-ii', difficulty: 'Easy', acceptance: 48.5 },
      { id: 121,  title: 'Best Time to Buy and Sell Stock', slug: 'best-time-to-buy-and-sell-stock', difficulty: 'Easy', acceptance: 56.7 },
      { id: 3,    title: 'Longest Substring Without Repeating Characters', slug: 'longest-substring-without-repeating-characters', difficulty: 'Medium', acceptance: 38.9 },
      { id: 424,  title: 'Longest Repeating Character Replacement', slug: 'longest-repeating-character-replacement', difficulty: 'Medium', acceptance: 59.5 },
      { id: 567,  title: 'Permutation in String', slug: 'permutation-in-string', difficulty: 'Medium', acceptance: 48.7 },
      { id: 209,  title: 'Minimum Size Subarray Sum', slug: 'minimum-size-subarray-sum', difficulty: 'Medium', acceptance: 52.5 },
      { id: 658,  title: 'Find K Closest Elements', slug: 'find-k-closest-elements', difficulty: 'Medium', acceptance: 57.5 },
      { id: 76,   title: 'Minimum Window Substring', slug: 'minimum-window-substring', difficulty: 'Hard', acceptance: 47.4 },
      { id: 239,  title: 'Sliding Window Maximum', slug: 'sliding-window-maximum', difficulty: 'Hard', acceptance: 48.7 },
    ],
  },
  {
    name: 'Stack', emoji: '🥞', color: 'orange',
    questions: [
      { id: 682,  title: 'Baseball Game', slug: 'baseball-game', difficulty: 'Easy', acceptance: 75.6 },
      { id: 20,   title: 'Valid Parentheses', slug: 'valid-parentheses', difficulty: 'Easy', acceptance: 44.1 },
      { id: 225,  title: 'Implement Stack Using Queues', slug: 'implement-stack-using-queues', difficulty: 'Easy', acceptance: 69.4 },
      { id: 232,  title: 'Implement Queue using Stacks', slug: 'implement-queue-using-stacks', difficulty: 'Easy', acceptance: 69.2 },
      { id: 155,  title: 'Min Stack', slug: 'min-stack', difficulty: 'Medium', acceptance: 58.0 },
      { id: 150,  title: 'Evaluate Reverse Polish Notation', slug: 'evaluate-reverse-polish-notation', difficulty: 'Medium', acceptance: 57.6 },
      { id: 735,  title: 'Asteroid Collision', slug: 'asteroid-collision', difficulty: 'Medium', acceptance: 48.5 },
      { id: 739,  title: 'Daily Temperatures', slug: 'daily-temperatures', difficulty: 'Medium', acceptance: 68.6 },
      { id: 901,  title: 'Online Stock Span', slug: 'online-stock-span', difficulty: 'Medium', acceptance: 69.2 },
      { id: 853,  title: 'Car Fleet', slug: 'car-fleet', difficulty: 'Medium', acceptance: 55.0 },
      { id: 71,   title: 'Simplify Path', slug: 'simplify-path', difficulty: 'Medium', acceptance: 46.8 },
      { id: 394,  title: 'Decode String', slug: 'decode-string', difficulty: 'Medium', acceptance: 63.5 },
      { id: 895,  title: 'Maximum Frequency Stack', slug: 'maximum-frequency-stack', difficulty: 'Hard', acceptance: 67.1 },
      { id: 84,   title: 'Largest Rectangle in Histogram', slug: 'largest-rectangle-in-histogram', difficulty: 'Hard', acceptance: 49.7 },
    ],
  },
  {
    name: 'Binary Search', emoji: '🔍', color: 'violet',
    questions: [
      { id: 704,  title: 'Binary Search', slug: 'binary-search', difficulty: 'Easy', acceptance: 60.8 },
      { id: 35,   title: 'Search Insert Position', slug: 'search-insert-position', difficulty: 'Easy', acceptance: 61.4 },
      { id: 374,  title: 'Guess Number Higher or Lower', slug: 'guess-number-higher-or-lower', difficulty: 'Easy', acceptance: 61.4 },
      { id: 69,   title: 'Sqrt(x)', slug: 'sqrtx', difficulty: 'Easy', acceptance: 40.5 },
      { id: 74,   title: 'Search a 2D Matrix', slug: 'search-a-2d-matrix', difficulty: 'Medium', acceptance: 53.8 },
      { id: 875,  title: 'Koko Eating Bananas', slug: 'koko-eating-bananas', difficulty: 'Medium', acceptance: 49.9 },
      { id: 1011, title: 'Capacity to Ship Packages Within D Days', slug: 'capacity-to-ship-packages-within-d-days', difficulty: 'Medium', acceptance: 71.6 },
      { id: 153,  title: 'Find Minimum in Rotated Sorted Array', slug: 'find-minimum-in-rotated-sorted-array', difficulty: 'Medium', acceptance: 54.1 },
      { id: 33,   title: 'Search in Rotated Sorted Array', slug: 'search-in-rotated-sorted-array', difficulty: 'Medium', acceptance: 44.4 },
      { id: 81,   title: 'Search in Rotated Sorted Array II', slug: 'search-in-rotated-sorted-array-ii', difficulty: 'Medium', acceptance: 39.2 },
      { id: 981,  title: 'Time Based Key-Value Store', slug: 'time-based-key-value-store', difficulty: 'Medium', acceptance: 49.9 },
      { id: 410,  title: 'Split Array Largest Sum', slug: 'split-array-largest-sum', difficulty: 'Hard', acceptance: 58.5 },
      { id: 4,    title: 'Median of Two Sorted Arrays', slug: 'median-of-two-sorted-arrays', difficulty: 'Hard', acceptance: 46.4 },
      { id: 1095, title: 'Find in Mountain Array', slug: 'find-in-mountain-array', difficulty: 'Hard', acceptance: 36.2 },
    ],
  },
  {
    name: 'Linked List', emoji: '🔗', color: 'teal',
    questions: [
      { id: 206,  title: 'Reverse Linked List', slug: 'reverse-linked-list', difficulty: 'Easy', acceptance: 80.5 },
      { id: 21,   title: 'Merge Two Sorted Lists', slug: 'merge-two-sorted-lists', difficulty: 'Easy', acceptance: 68.2 },
      { id: 141,  title: 'Linked List Cycle', slug: 'linked-list-cycle', difficulty: 'Easy', acceptance: 54.2 },
      { id: 143,  title: 'Reorder List', slug: 'reorder-list', difficulty: 'Medium', acceptance: 65.1 },
      { id: 19,   title: 'Remove Nth Node From End of List', slug: 'remove-nth-node-from-end-of-list', difficulty: 'Medium', acceptance: 51.4 },
      { id: 138,  title: 'Copy List with Random Pointer', slug: 'copy-list-with-random-pointer', difficulty: 'Medium', acceptance: 62.8 },
      { id: 2,    title: 'Add Two Numbers', slug: 'add-two-numbers', difficulty: 'Medium', acceptance: 48.3 },
      { id: 287,  title: 'Find the Duplicate Number', slug: 'find-the-duplicate-number', difficulty: 'Medium', acceptance: 64.2 },
      { id: 92,   title: 'Reverse Linked List II', slug: 'reverse-linked-list-ii', difficulty: 'Medium', acceptance: 51.5 },
      { id: 622,  title: 'Design Circular Queue', slug: 'design-circular-queue', difficulty: 'Medium', acceptance: 57.8 },
      { id: 146,  title: 'LRU Cache', slug: 'lru-cache', difficulty: 'Medium', acceptance: 47.2 },
      { id: 460,  title: 'LFU Cache', slug: 'lfu-cache', difficulty: 'Hard', acceptance: 47.4 },
      { id: 23,   title: 'Merge k Sorted Lists', slug: 'merge-k-sorted-lists', difficulty: 'Hard', acceptance: 59.4 },
      { id: 25,   title: 'Reverse Nodes in k-Group', slug: 'reverse-nodes-in-k-group', difficulty: 'Hard', acceptance: 65.9 },
    ],
  },
  {
    name: 'Trees', emoji: '🌳', color: 'green',
    questions: [
      { id: 94,   title: 'Binary Tree Inorder Traversal', slug: 'binary-tree-inorder-traversal', difficulty: 'Easy', acceptance: 78.4 },
      { id: 144,  title: 'Binary Tree Preorder Traversal', slug: 'binary-tree-preorder-traversal', difficulty: 'Easy', acceptance: 72.5 },
      { id: 145,  title: 'Binary Tree Postorder Traversal', slug: 'binary-tree-postorder-traversal', difficulty: 'Easy', acceptance: 77.4 },
      { id: 226,  title: 'Invert Binary Tree', slug: 'invert-binary-tree', difficulty: 'Easy', acceptance: 80.0 },
      { id: 104,  title: 'Maximum Depth of Binary Tree', slug: 'maximum-depth-of-binary-tree', difficulty: 'Easy', acceptance: 78.1 },
      { id: 543,  title: 'Diameter of Binary Tree', slug: 'diameter-of-binary-tree', difficulty: 'Easy', acceptance: 65.4 },
      { id: 110,  title: 'Balanced Binary Tree', slug: 'balanced-binary-tree', difficulty: 'Easy', acceptance: 58.2 },
      { id: 100,  title: 'Same Tree', slug: 'same-tree', difficulty: 'Easy', acceptance: 67.0 },
      { id: 572,  title: 'Subtree of Another Tree', slug: 'subtree-of-another-tree', difficulty: 'Easy', acceptance: 51.5 },
      { id: 235,  title: 'Lowest Common Ancestor of a Binary Search Tree', slug: 'lowest-common-ancestor-of-a-binary-search-tree', difficulty: 'Medium', acceptance: 70.5 },
      { id: 701,  title: 'Insert into a Binary Search Tree', slug: 'insert-into-a-binary-search-tree', difficulty: 'Medium', acceptance: 66.7 },
      { id: 450,  title: 'Delete Node in a BST', slug: 'delete-node-in-a-bst', difficulty: 'Medium', acceptance: 52.8 },
      { id: 102,  title: 'Binary Tree Level Order Traversal', slug: 'binary-tree-level-order-traversal', difficulty: 'Medium', acceptance: 72.5 },
      { id: 199,  title: 'Binary Tree Right Side View', slug: 'binary-tree-right-side-view', difficulty: 'Medium', acceptance: 70.0 },
      { id: 427,  title: 'Construct Quad Tree', slug: 'construct-quad-tree', difficulty: 'Medium', acceptance: 71.1 },
      { id: 1448, title: 'Count Good Nodes in Binary Tree', slug: 'count-good-nodes-in-binary-tree', difficulty: 'Medium', acceptance: 73.8 },
      { id: 98,   title: 'Validate Binary Search Tree', slug: 'validate-binary-search-tree', difficulty: 'Medium', acceptance: 35.7 },
      { id: 230,  title: 'Kth Smallest Element in a BST', slug: 'kth-smallest-element-in-a-bst', difficulty: 'Medium', acceptance: 76.7 },
      { id: 105,  title: 'Construct Binary Tree from Preorder and Inorder Traversal', slug: 'construct-binary-tree-from-preorder-and-inorder-traversal', difficulty: 'Medium', acceptance: 68.7 },
      { id: 337,  title: 'House Robber III', slug: 'house-robber-iii', difficulty: 'Medium', acceptance: 56.1 },
      { id: 1325, title: 'Delete Leaves With a Given Value', slug: 'delete-leaves-with-a-given-value', difficulty: 'Medium', acceptance: 82.1 },
      { id: 124,  title: 'Binary Tree Maximum Path Sum', slug: 'binary-tree-maximum-path-sum', difficulty: 'Hard', acceptance: 42.2 },
      { id: 297,  title: 'Serialize and Deserialize Binary Tree', slug: 'serialize-and-deserialize-binary-tree', difficulty: 'Hard', acceptance: 60.6 },
    ],
  },
  {
    name: 'Heap / Priority Queue', emoji: '🏔️', color: 'rose',
    questions: [
      { id: 703,  title: 'Kth Largest Element in a Stream', slug: 'kth-largest-element-in-a-stream', difficulty: 'Easy', acceptance: 60.9 },
      { id: 1046, title: 'Last Stone Weight', slug: 'last-stone-weight', difficulty: 'Easy', acceptance: 66.4 },
      { id: 973,  title: 'K Closest Points to Origin', slug: 'k-closest-points-to-origin', difficulty: 'Medium', acceptance: 68.9 },
      { id: 215,  title: 'Kth Largest Element in an Array', slug: 'kth-largest-element-in-an-array', difficulty: 'Medium', acceptance: 68.9 },
      { id: 621,  title: 'Task Scheduler', slug: 'task-scheduler', difficulty: 'Medium', acceptance: 63.0 },
      { id: 355,  title: 'Design Twitter', slug: 'design-twitter', difficulty: 'Medium', acceptance: 44.5 },
      { id: 1834, title: 'Single-Threaded CPU', slug: 'single-threaded-cpu', difficulty: 'Medium', acceptance: 55.8 },
      { id: 767,  title: 'Reorganize String', slug: 'reorganize-string', difficulty: 'Medium', acceptance: 58.5 },
      { id: 1405, title: 'Longest Happy String', slug: 'longest-happy-string', difficulty: 'Medium', acceptance: 62.6 },
      { id: 1094, title: 'Car Pooling', slug: 'car-pooling', difficulty: 'Medium', acceptance: 64.2 },
      { id: 295,  title: 'Find Median from Data Stream', slug: 'find-median-from-data-stream', difficulty: 'Hard', acceptance: 54.4 },
      { id: 502,  title: 'IPO', slug: 'ipo', difficulty: 'Hard', acceptance: 51.8 },
    ],
  },
  {
    name: 'Backtracking', emoji: '🔙', color: 'amber',
    questions: [
      { id: 1863, title: 'Sum of All Subset XOR Totals', slug: 'sum-of-all-subset-xor-totals', difficulty: 'Easy', acceptance: 91.9 },
      { id: 78,   title: 'Subsets', slug: 'subsets', difficulty: 'Medium', acceptance: 82.3 },
      { id: 39,   title: 'Combination Sum', slug: 'combination-sum', difficulty: 'Medium', acceptance: 76.4 },
      { id: 40,   title: 'Combination Sum II', slug: 'combination-sum-ii', difficulty: 'Medium', acceptance: 59.3 },
      { id: 77,   title: 'Combinations', slug: 'combinations', difficulty: 'Medium', acceptance: 77.3 },
      { id: 46,   title: 'Permutations', slug: 'permutations', difficulty: 'Medium', acceptance: 81.9 },
      { id: 90,   title: 'Subsets II', slug: 'subsets-ii', difficulty: 'Medium', acceptance: 61.2 },
      { id: 47,   title: 'Permutations II', slug: 'permutations-ii', difficulty: 'Medium', acceptance: 62.9 },
      { id: 22,   title: 'Generate Parentheses', slug: 'generate-parentheses', difficulty: 'Medium', acceptance: 78.6 },
      { id: 79,   title: 'Word Search', slug: 'word-search', difficulty: 'Medium', acceptance: 47.2 },
      { id: 131,  title: 'Palindrome Partitioning', slug: 'palindrome-partitioning', difficulty: 'Medium', acceptance: 74.0 },
      { id: 17,   title: 'Letter Combinations of a Phone Number', slug: 'letter-combinations-of-a-phone-number', difficulty: 'Medium', acceptance: 65.9 },
      { id: 473,  title: 'Matchsticks to Square', slug: 'matchsticks-to-square', difficulty: 'Medium', acceptance: 42.5 },
      { id: 698,  title: 'Partition to K Equal Sum Subsets', slug: 'partition-to-k-equal-sum-subsets', difficulty: 'Medium', acceptance: 42.3 },
      { id: 51,   title: 'N-Queens', slug: 'n-queens', difficulty: 'Hard', acceptance: 75.4 },
      { id: 52,   title: 'N-Queens II', slug: 'n-queens-ii', difficulty: 'Hard', acceptance: 82.3 },
      { id: 140,  title: 'Word Break II', slug: 'word-break-ii', difficulty: 'Hard', acceptance: 47.8 },
    ],
  },
  {
    name: 'Tries', emoji: '🔤', color: 'fuchsia',
    questions: [
      { id: 208,  title: 'Implement Trie (Prefix Tree)', slug: 'implement-trie-prefix-tree', difficulty: 'Medium', acceptance: 69.4 },
      { id: 211,  title: 'Design Add and Search Words Data Structure', slug: 'design-add-and-search-words-data-structure', difficulty: 'Medium', acceptance: 48.4 },
      { id: 2707, title: 'Extra Characters in a String', slug: 'extra-characters-in-a-string', difficulty: 'Medium', acceptance: 55.7 },
      { id: 212,  title: 'Word Search II', slug: 'word-search-ii', difficulty: 'Hard', acceptance: 38.4 },
    ],
  },
  {
    name: 'Graphs', emoji: '🕸️', color: 'blue',
    questions: [
      { id: 953,  title: 'Verifying an Alien Dictionary', slug: 'verifying-an-alien-dictionary', difficulty: 'Easy', acceptance: 70.6 },
      { id: 463,  title: 'Island Perimeter', slug: 'island-perimeter', difficulty: 'Easy', acceptance: 73.4 },
      { id: 997,  title: 'Find the Town Judge', slug: 'find-the-town-judge', difficulty: 'Easy', acceptance: 52.1 },
      { id: 200,  title: 'Number of Islands', slug: 'number-of-islands', difficulty: 'Medium', acceptance: 64.2 },
      { id: 695,  title: 'Max Area of Island', slug: 'max-area-of-island', difficulty: 'Medium', acceptance: 73.9 },
      { id: 133,  title: 'Clone Graph', slug: 'clone-graph', difficulty: 'Medium', acceptance: 65.2 },
      { id: 286,  title: 'Walls and Gates', slug: 'walls-and-gates', difficulty: 'Medium', acceptance: 63.9 },
      { id: 994,  title: 'Rotting Oranges', slug: 'rotting-oranges', difficulty: 'Medium', acceptance: 58.5 },
      { id: 417,  title: 'Pacific Atlantic Water Flow', slug: 'pacific-atlantic-water-flow', difficulty: 'Medium', acceptance: 60.9 },
      { id: 130,  title: 'Surrounded Regions', slug: 'surrounded-regions', difficulty: 'Medium', acceptance: 45.2 },
      { id: 752,  title: 'Open the Lock', slug: 'open-the-lock', difficulty: 'Medium', acceptance: 57.4 },
      { id: 207,  title: 'Course Schedule', slug: 'course-schedule', difficulty: 'Medium', acceptance: 51.3 },
      { id: 210,  title: 'Course Schedule II', slug: 'course-schedule-ii', difficulty: 'Medium', acceptance: 55.4 },
      { id: 261,  title: 'Graph Valid Tree', slug: 'graph-valid-tree', difficulty: 'Medium', acceptance: 50.0 },
      { id: 1462, title: 'Course Schedule IV', slug: 'course-schedule-iv', difficulty: 'Medium', acceptance: 52.8 },
      { id: 323,  title: 'Number of Connected Components in an Undirected Graph', slug: 'number-of-connected-components-in-an-undirected-graph', difficulty: 'Medium', acceptance: 64.9 },
      { id: 684,  title: 'Redundant Connection', slug: 'redundant-connection', difficulty: 'Medium', acceptance: 67.5 },
      { id: 721,  title: 'Accounts Merge', slug: 'accounts-merge', difficulty: 'Medium', acceptance: 62.0 },
      { id: 399,  title: 'Evaluate Division', slug: 'evaluate-division', difficulty: 'Medium', acceptance: 62.7 },
      { id: 310,  title: 'Minimum Height Trees', slug: 'minimum-height-trees', difficulty: 'Medium', acceptance: 47.5 },
      { id: 127,  title: 'Word Ladder', slug: 'word-ladder', difficulty: 'Hard', acceptance: 45.4 },
    ],
  },
  {
    name: 'Advanced Graphs', emoji: '🗺️', color: 'purple',
    questions: [
      { id: 1631, title: 'Path with Minimum Effort', slug: 'path-with-minimum-effort', difficulty: 'Medium', acceptance: 63.1 },
      { id: 743,  title: 'Network Delay Time', slug: 'network-delay-time', difficulty: 'Medium', acceptance: 60.2 },
      { id: 332,  title: 'Reconstruct Itinerary', slug: 'reconstruct-itinerary', difficulty: 'Hard', acceptance: 44.5 },
      { id: 1584, title: 'Min Cost to Connect All Points', slug: 'min-cost-to-connect-all-points', difficulty: 'Medium', acceptance: 70.8 },
      { id: 778,  title: 'Swim in Rising Water', slug: 'swim-in-rising-water', difficulty: 'Hard', acceptance: 67.8 },
      { id: 269,  title: 'Alien Dictionary', slug: 'alien-dictionary', difficulty: 'Hard', acceptance: 37.2 },
      { id: 787,  title: 'Cheapest Flights Within K Stops', slug: 'cheapest-flights-within-k-stops', difficulty: 'Medium', acceptance: 41.7 },
      { id: 1489, title: 'Find Critical and Pseudo Critical Edges in MST', slug: 'find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree', difficulty: 'Hard', acceptance: 53.7 },
      { id: 2392, title: 'Build a Matrix With Conditions', slug: 'build-a-matrix-with-conditions', difficulty: 'Hard', acceptance: 62.8 },
      { id: 2709, title: 'Greatest Common Divisor Traversal', slug: 'greatest-common-divisor-traversal', difficulty: 'Hard', acceptance: 55.0 },
    ],
  },
  {
    name: '1-D Dynamic Programming', emoji: '📈', color: 'emerald',
    questions: [
      { id: 70,   title: 'Climbing Stairs', slug: 'climbing-stairs', difficulty: 'Easy', acceptance: 54.0 },
      { id: 746,  title: 'Min Cost Climbing Stairs', slug: 'min-cost-climbing-stairs', difficulty: 'Easy', acceptance: 68.2 },
      { id: 1137, title: 'N-th Tribonacci Number', slug: 'n-th-tribonacci-number', difficulty: 'Easy', acceptance: 64.7 },
      { id: 198,  title: 'House Robber', slug: 'house-robber', difficulty: 'Medium', acceptance: 53.2 },
      { id: 213,  title: 'House Robber II', slug: 'house-robber-ii', difficulty: 'Medium', acceptance: 44.8 },
      { id: 5,    title: 'Longest Palindromic Substring', slug: 'longest-palindromic-substring', difficulty: 'Medium', acceptance: 37.7 },
      { id: 647,  title: 'Palindromic Substrings', slug: 'palindromic-substrings', difficulty: 'Medium', acceptance: 72.7 },
      { id: 91,   title: 'Decode Ways', slug: 'decode-ways', difficulty: 'Medium', acceptance: 37.9 },
      { id: 322,  title: 'Coin Change', slug: 'coin-change', difficulty: 'Medium', acceptance: 48.3 },
      { id: 152,  title: 'Maximum Product Subarray', slug: 'maximum-product-subarray', difficulty: 'Medium', acceptance: 36.3 },
      { id: 139,  title: 'Word Break', slug: 'word-break', difficulty: 'Medium', acceptance: 49.4 },
      { id: 300,  title: 'Longest Increasing Subsequence', slug: 'longest-increasing-subsequence', difficulty: 'Medium', acceptance: 59.3 },
      { id: 416,  title: 'Partition Equal Subset Sum', slug: 'partition-equal-subset-sum', difficulty: 'Medium', acceptance: 49.4 },
      { id: 377,  title: 'Combination Sum IV', slug: 'combination-sum-iv', difficulty: 'Medium', acceptance: 53.5 },
      { id: 279,  title: 'Perfect Squares', slug: 'perfect-squares', difficulty: 'Medium', acceptance: 56.2 },
      { id: 343,  title: 'Integer Break', slug: 'integer-break', difficulty: 'Medium', acceptance: 60.0 },
      { id: 913,  title: 'Stone Game III', slug: 'stone-game-iii', difficulty: 'Hard', acceptance: 59.2 },
    ],
  },
  {
    name: '2-D Dynamic Programming', emoji: '🔢', color: 'lime',
    questions: [
      { id: 62,   title: 'Unique Paths', slug: 'unique-paths', difficulty: 'Medium', acceptance: 66.8 },
      { id: 63,   title: 'Unique Paths II', slug: 'unique-paths-ii', difficulty: 'Medium', acceptance: 43.3 },
      { id: 64,   title: 'Minimum Path Sum', slug: 'minimum-path-sum', difficulty: 'Medium', acceptance: 69.2 },
      { id: 1143, title: 'Longest Common Subsequence', slug: 'longest-common-subsequence', difficulty: 'Medium', acceptance: 59.1 },
      { id: 1049, title: 'Last Stone Weight II', slug: 'last-stone-weight-ii', difficulty: 'Medium', acceptance: 55.3 },
      { id: 309,  title: 'Best Time to Buy and Sell Stock with Cooldown', slug: 'best-time-to-buy-and-sell-stock-with-cooldown', difficulty: 'Medium', acceptance: 62.0 },
      { id: 518,  title: 'Coin Change II', slug: 'coin-change-ii', difficulty: 'Medium', acceptance: 60.1 },
      { id: 494,  title: 'Target Sum', slug: 'target-sum', difficulty: 'Medium', acceptance: 52.1 },
      { id: 97,   title: 'Interleaving String', slug: 'interleaving-string', difficulty: 'Medium', acceptance: 43.9 },
      { id: 877,  title: 'Stone Game', slug: 'stone-game', difficulty: 'Medium', acceptance: 68.5 },
      { id: 1140, title: 'Stone Game II', slug: 'stone-game-ii', difficulty: 'Medium', acceptance: 63.7 },
      { id: 329,  title: 'Longest Increasing Path in a Matrix', slug: 'longest-increasing-path-in-a-matrix', difficulty: 'Hard', acceptance: 56.5 },
      { id: 115,  title: 'Distinct Subsequences', slug: 'distinct-subsequences', difficulty: 'Hard', acceptance: 51.8 },
      { id: 72,   title: 'Edit Distance', slug: 'edit-distance', difficulty: 'Medium', acceptance: 60.5 },
      { id: 312,  title: 'Burst Balloons', slug: 'burst-balloons', difficulty: 'Hard', acceptance: 63.3 },
      { id: 10,   title: 'Regular Expression Matching', slug: 'regular-expression-matching', difficulty: 'Hard', acceptance: 30.8 },
    ],
  },
  {
    name: 'Greedy', emoji: '💰', color: 'yellow',
    questions: [
      { id: 860,  title: 'Lemonade Change', slug: 'lemonade-change', difficulty: 'Easy', acceptance: 54.2 },
      { id: 53,   title: 'Maximum Subarray', slug: 'maximum-subarray', difficulty: 'Medium', acceptance: 53.2 },
      { id: 918,  title: 'Maximum Sum Circular Subarray', slug: 'maximum-sum-circular-subarray', difficulty: 'Medium', acceptance: 47.0 },
      { id: 978,  title: 'Longest Turbulent Subarray', slug: 'longest-turbulent-subarray', difficulty: 'Medium', acceptance: 51.8 },
      { id: 55,   title: 'Jump Game', slug: 'jump-game', difficulty: 'Medium', acceptance: 40.8 },
      { id: 45,   title: 'Jump Game II', slug: 'jump-game-ii', difficulty: 'Medium', acceptance: 42.8 },
      { id: 1871, title: 'Jump Game VII', slug: 'jump-game-vii', difficulty: 'Medium', acceptance: 32.5 },
      { id: 134,  title: 'Gas Station', slug: 'gas-station', difficulty: 'Medium', acceptance: 47.9 },
      { id: 846,  title: 'Hand of Straights', slug: 'hand-of-straights', difficulty: 'Medium', acceptance: 57.9 },
      { id: 649,  title: 'Dota2 Senate', slug: 'dota2-senate', difficulty: 'Medium', acceptance: 43.5 },
      { id: 1899, title: 'Merge Triplets to Form Target Triplet', slug: 'merge-triplets-to-form-target-triplet', difficulty: 'Medium', acceptance: 69.0 },
      { id: 763,  title: 'Partition Labels', slug: 'partition-labels', difficulty: 'Medium', acceptance: 81.9 },
      { id: 678,  title: 'Valid Parenthesis String', slug: 'valid-parenthesis-string', difficulty: 'Medium', acceptance: 40.0 },
      { id: 135,  title: 'Candy', slug: 'candy', difficulty: 'Hard', acceptance: 44.0 },
    ],
  },
  {
    name: 'Intervals', emoji: '📏', color: 'pink',
    questions: [
      { id: 57,   title: 'Insert Interval', slug: 'insert-interval', difficulty: 'Medium', acceptance: 45.1 },
      { id: 56,   title: 'Merge Intervals', slug: 'merge-intervals', difficulty: 'Medium', acceptance: 51.7 },
      { id: 435,  title: 'Non-overlapping Intervals', slug: 'non-overlapping-intervals', difficulty: 'Medium', acceptance: 57.0 },
      { id: 252,  title: 'Meeting Rooms', slug: 'meeting-rooms', difficulty: 'Easy', acceptance: 59.4 },
      { id: 253,  title: 'Meeting Rooms II', slug: 'meeting-rooms-ii', difficulty: 'Medium', acceptance: 52.6 },
      { id: 2402, title: 'Meeting Rooms III', slug: 'meeting-rooms-iii', difficulty: 'Hard', acceptance: 47.8 },
      { id: 1851, title: 'Minimum Interval to Include Each Query', slug: 'minimum-interval-to-include-each-query', difficulty: 'Hard', acceptance: 54.3 },
    ],
  },
  {
    name: 'Math & Geometry', emoji: '📐', color: 'slate',
    questions: [
      { id: 168,  title: 'Excel Sheet Column Title', slug: 'excel-sheet-column-title', difficulty: 'Easy', acceptance: 43.3 },
      { id: 1071, title: 'Greatest Common Divisor of Strings', slug: 'greatest-common-divisor-of-strings', difficulty: 'Easy', acceptance: 55.3 },
      { id: 867,  title: 'Transpose Matrix', slug: 'transpose-matrix', difficulty: 'Easy', acceptance: 77.0 },
      { id: 48,   title: 'Rotate Image', slug: 'rotate-image', difficulty: 'Medium', acceptance: 79.6 },
      { id: 54,   title: 'Spiral Matrix', slug: 'spiral-matrix', difficulty: 'Medium', acceptance: 56.6 },
      { id: 73,   title: 'Set Matrix Zeroes', slug: 'set-matrix-zeroes', difficulty: 'Medium', acceptance: 62.8 },
      { id: 202,  title: 'Happy Number', slug: 'happy-number', difficulty: 'Easy', acceptance: 59.6 },
      { id: 66,   title: 'Plus One', slug: 'plus-one', difficulty: 'Easy', acceptance: 49.9 },
      { id: 13,   title: 'Roman to Integer', slug: 'roman-to-integer', difficulty: 'Easy', acceptance: 64.2 },
      { id: 50,   title: 'Pow(x, n)', slug: 'powx-n', difficulty: 'Medium', acceptance: 38.6 },
      { id: 43,   title: 'Multiply Strings', slug: 'multiply-strings', difficulty: 'Medium', acceptance: 44.0 },
      { id: 2013, title: 'Detect Squares', slug: 'detect-squares', difficulty: 'Medium', acceptance: 52.5 },
      { id: 2807, title: 'Insert Greatest Common Divisors in Linked List', slug: 'insert-greatest-common-divisors-in-linked-list', difficulty: 'Medium', acceptance: 89.2 },
    ],
  },
  {
    name: 'Bit Manipulation', emoji: '⚡', color: 'red',
    questions: [
      { id: 136,  title: 'Single Number', slug: 'single-number', difficulty: 'Easy', acceptance: 77.6 },
      { id: 191,  title: 'Number of 1 Bits', slug: 'number-of-1-bits', difficulty: 'Easy', acceptance: 76.7 },
      { id: 338,  title: 'Counting Bits', slug: 'counting-bits', difficulty: 'Easy', acceptance: 80.5 },
      { id: 67,   title: 'Add Binary', slug: 'add-binary', difficulty: 'Easy', acceptance: 56.8 },
      { id: 190,  title: 'Reverse Bits', slug: 'reverse-bits', difficulty: 'Easy', acceptance: 68.2 },
      { id: 268,  title: 'Missing Number', slug: 'missing-number', difficulty: 'Easy', acceptance: 71.9 },
      { id: 371,  title: 'Sum of Two Integers', slug: 'sum-of-two-integers', difficulty: 'Medium', acceptance: 55.4 },
      { id: 7,    title: 'Reverse Integer', slug: 'reverse-integer', difficulty: 'Medium', acceptance: 31.8 },
      { id: 201,  title: 'Bitwise AND of Numbers Range', slug: 'bitwise-and-of-numbers-range', difficulty: 'Medium', acceptance: 44.0 },
      { id: 3133, title: 'Minimum Array End', slug: 'minimum-array-end', difficulty: 'Medium', acceptance: 55.5 },
    ],
  },
]

export const ALL_NC250_IDS = new Set(
  NEETCODE_250.flatMap(c => c.questions.map(q => q.id))
)

export const NC250_TOTAL = NEETCODE_250.reduce((n, c) => n + c.questions.length, 0)
